/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        uiRacManagerSettings: "RAC Manager Settings",
        uiMapWidget: "Map widget",
        uiSelectTheMapThatContainsYour: "إختار الخريطة التي تحتوي على طبقات خدماتك الخاصة",
        uiTicketsLayerTitle: "Tickets Layer Title",
        uiMustMatchTheLayerTitleExactly: "يجب أن يطابق عنوان الطبعة كما يظهر في خريطة الإنترنت",
        uiCommentsTableName: "قائمة الأسماء",
        uiTokenBasedMatchUnderscoresAndSpaces: "وتعالج المطابقة القائمة على الكينات - التأكيدات والمساحات نفسها )المراعية للحالات(.",
        uiPhotosTableName: "اسم الجدول",
        uiSurveyTableName: "الجدول البياني",
        uiOrganizationName: "الاسم",
        uiShownAsTheAuthorAndSubtitle: "تظهر كصاحبة لصادرات إكسل واسمها الفرعي.",
        uiHelpButtonAndGuide: "زر المساعدة والدليل",
        uiShowTheHelpButtonAndThe: "أظهري زر المساعدة و التلميح الأول",
        uiShowsAHelpButtonAtThe: "يُظهر زراً للمساعدة في أعلى اليمين من الوادي و تلميح لمرة واحدة للمستعملين الجدد أطفأه من أجل الـ(كيوسك) أو الاستخدامات المدمجة",
        uiRequiredWebMapSetup: "⚙️ Required web Map Setup",
        uiTheCommentsSurveysAndPhotosTables: "The Comments, Surveys, and Photos tables must be",
        uiExplicitlyAddedToYourWebMap: "أضيفت بشكل صريح لخارطة الإنترنت",
        uiInPortalMapViewerPublishingThe: "- نشر مجلة \" فيوير \" وحدها لا يكفي.",
        uiOpenYourWebMapInPortal: "أفتح خريطة موقعك في \"بورت ماب فيوير\"",
        uiAddLayerBrowseTo: "أضف طبقة",
        uiReportaconcernManagerFeatureserver: "ReportAConcern Manager / FeatureServer",
        uiAddEachOfTheseAs: "يضاف كل واحد من هذه",
        uiTables: "الجداول",
        uiNotLayers: "(ليس طبقات):",
        uiTicketComments: "التذاكر - الاستحقاقات",
        uiSurveyResponses: "الدراسة الاستقصائية - الردود",
        uiTicketPhotosMeta: "Ticket Photos Meta",
        uiSaveTheWebMap: "أنقذ خريطة الإنترنت",
        uiToVerify: "للتحقق:",
        uiOpenTheBrowserConsoleAfterThe: "أفتحوا حزمة الـ (بروسر) بعد حمولات الـ (وادج) وأبحثوا عن خطوط",
        uiRacManager: "RAC Manager:",
        uiNotFound: "لا يوجد",
        uiThatTableIsMissingFromThe: "تلك الطاولة مفقودة من خريطة الإنترنت",
        uiAllAuthFlowsThroughThePortal: "فكل ذلك يتدفق من خلال دورة الميناء - لا حاجة إلى مداخل إضافية. لتقييد الوصول، مشاركة التطبيق مع مجموعة بورتال.",
        tickets: "تذاكر",
        eachTableShouldShowItsTitle: ". Each table should show its title — if any say"
      })
    }
  }
})
