/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        uiRacManagerSettings: "Настройки на RAC мениджър",
        uiMapWidget: "Name",
        uiSelectTheMapThatContainsYour: "Изберете карта, която съдържа Вашите RAC функции услуги слоеве.",
        uiTicketsLayerTitle: "Tickets Layer Заглавие",
        uiMustMatchTheLayerTitleExactly: "Трябва да съответства на заглавието на слой точно както се появява в уеб картата.",
        uiCommentsTableName: "Коментари Таблица Име",
        uiTokenBasedMatchUnderscoresAndSpaces: "Token-базирани мачове готварски и пространства се третират по същия начин (нечувствителен случай).",
        uiPhotosTableName: "Име на таблицата със снимки",
        uiSurveyTableName: "Име на таблицата за проучване",
        uiOrganizationName: "Име на организацията",
        uiShownAsTheAuthorAndSubtitle: "Показан като автор и субтитри на Excel износ.",
        uiHelpButtonAndGuide: "Помощен бутон и ръководство",
        uiShowTheHelpButtonAndThe: "Показване на бутона за помощ и на намека за първото пускане",
        uiShowsAHelpButtonAtThe: "Показване на бутон за помощ в горния десен ъгъл на джаджата и еднократно намекване за нови потребители. Изключете го за павилиони или вградени приложения.",
        uiRequiredWebMapSetup: "Настройка на необходимата уеб карта",
        uiTheCommentsSurveysAndPhotosTables: "Коментарите, проучвания и снимки таблици трябва да бъдат",
        uiExplicitlyAddedToYourWebMap: "изрично добавена към вашата уеб карта",
        uiInPortalMapViewerPublishingThe: "в Портал Карта Viewer гонитба само FeatureServer не е достатъчно.",
        uiOpenYourWebMapInPortal: "Отворете уеб картата си в Portal Map Viewer",
        uiAddLayerBrowseTo: "Добавяне на слой → Преглед към",
        uiReportaconcernManagerFeatureserver: "ReportAConcern Manager / FeatureServer",
        uiAddEachOfTheseAs: "Добавяне на всяка от тези като",
        uiTables: "Таблици",
        uiNotLayers: "(не слоеве):",
        uiTicketComments: "Ticket Comments",
        uiSurveyResponses: "Survey Responses",
        uiTicketPhotosMeta: "Билет фотос мета",
        uiSaveTheWebMap: "Запис на уеб картата",
        uiToVerify: "За да се провери:",
        uiOpenTheBrowserConsoleAfterThe: "Отваряне на конзолата на браузъра след натоварване на джаджата и търсене на линии, започващи с",
        uiRacManager: "RAC мениджър:",
        uiNotFound: "Не е открит",
        uiThatTableIsMissingFromThe: "Тази маса липсва от картата.",
        uiAllAuthFlowsThroughThePortal: "Всички Auth потоци през Портал сесията не са необходими допълнителни символи. За да ограничите достъпа, споделете приложението с група портали.",
        tickets: "Билети",
        eachTableShouldShowItsTitle: ". Each table should show its title — if any say"
      })
    }
  }
})
