/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        uiRacManagerSettings: "Nastavení správce RAC",
        uiMapWidget: "Name",
        uiSelectTheMapThatContainsYour: "Vyberte mapu, která obsahuje vaše servisní vrstvy RAC.",
        uiTicketsLayerTitle: "Název vrstvy vstupenek",
        uiMustMatchTheLayerTitleExactly: "Musí se shodovat s titulem vrstvy přesně tak, jak se objeví na webové mapě.",
        uiCommentsTableName: "Poznámky Název tabulky",
        uiTokenBasedMatchUnderscoresAndSpaces: "Token- based match - podtržení a mezery jsou považovány za stejné (case- necitlivé).",
        uiPhotosTableName: "Fotografie Název stolu",
        uiSurveyTableName: "Název tabulky zjišťování",
        uiOrganizationName: "Název organizace",
        uiShownAsTheAuthorAndSubtitle: "Zobrazeno jako autor a titulek Excelu export.",
        uiHelpButtonAndGuide: "Tlačítko a průvodce",
        uiShowTheHelpButtonAndThe: "Zobrazit tlačítko Nápověda a náznak prvního spuštění",
        uiShowsAHelpButtonAtThe: "Zobrazí tlačítko Nápověda v pravé horní části widgetu a jednorázovou nápovědu pro nové uživatele. Vypněte to pro kiosek nebo vložené použití.",
        uiRequiredWebMapSetup: "Name",
        uiTheCommentsSurveysAndPhotosTables: "Komentáře, průzkumy a fotografie tabulky musí být",
        uiExplicitlyAddedToYourWebMap: "explicitně přidán do vaší webové mapy",
        uiInPortalMapViewerPublishingThe: "v Prohlížeči portálových map - publikování samotného FeatureServeru nestačí.",
        uiOpenYourWebMapInPortal: "Otevřete svou webovou mapu v Prohlížeči Portálů",
        uiAddLayerBrowseTo: "Přidat vrstvu → procházení do",
        uiReportaconcernManagerFeatureserver: "ReportAConcern _ Manager / FeatureServer",
        uiAddEachOfTheseAs: "Přidat každý z nich jako",
        uiTables: "Tabulky",
        uiNotLayers: "(ne vrstvy):",
        uiTicketComments: "Tiket _ Komentáře",
        uiSurveyResponses: "Průzkum _ Odpovědi",
        uiTicketPhotosMeta: "Lístek _ Fotografie _ Meta",
        uiSaveTheWebMap: "Uložit webovou mapu",
        uiToVerify: "Pro ověření:",
        uiOpenTheBrowserConsoleAfterThe: "Otevřete konzoli prohlížeče po načtení widget a hledejte řádky začínající",
        uiRacManager: "Manažer RAC:",
        uiNotFound: "NENÍ ZJIŠTĚNO",
        uiThatTableIsMissingFromThe: "Ten stůl chybí v mapě.",
        uiAllAuthFlowsThroughThePortal: "Všechny auty proudí přes Portál session - žádné další žetony potřebné. Chcete-li omezit přístup, sdílejte aplikaci se skupinou Portal.",
        tickets: "Vstupenky",
        eachTableShouldShowItsTitle: ". Each table should show its title — if any say"
      })
    }
  }
})
