/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        uiRacManagerSettings: "Settings διαχειριστή RAC",
        uiMapWidget: "Γραφικό συστατικό χάρτη",
        uiSelectTheMapThatContainsYour: "Επιλέξτε το χάρτη που περιέχει τα στρώματα υπηρεσιών λειτουργίας RAC σας.",
        uiTicketsLayerTitle: "Τίτλος στρώματος εισιτηρίων",
        uiMustMatchTheLayerTitleExactly: "Πρέπει να ταιριάζει με τον τίτλο στρώμα ακριβώς όπως εμφανίζεται στο χάρτη ιστού.",
        uiCommentsTableName: "Σχόλια Όνομα πίνακα",
        uiTokenBasedMatchUnderscoresAndSpaces: "Ταιριάζουν με βάση τα στοιχεία — υπογραμμίζουν και οι χώροι αντιμετωπίζονται με τον ίδιο τρόπο (αναίσθητη περίπτωση).",
        uiPhotosTableName: "Όνομα πίνακα φωτογραφιών",
        uiSurveyTableName: "Όνομα πίνακα έρευνας",
        uiOrganizationName: "Όνομα οργανισμού",
        uiShownAsTheAuthorAndSubtitle: "Εμφανίστηκε ως ο συγγραφέας και υπότιτλος της εξαγωγής Excel.",
        uiHelpButtonAndGuide: "Κουμπί και οδηγός βοήθειας",
        uiShowTheHelpButtonAndThe: "Εμφάνιση του κουμπιού Βοήθειας και της πρώτης υπόδειξης",
        uiShowsAHelpButtonAtThe: "Εμφανίζει ένα κουμπί Βοήθειας στο πάνω δεξί μέρος του γραφικού συστατικού και μια μοναδική υπόδειξη για νέους χρήστες. Κλείστο για κιόσκια ή για ενσωματωμένες χρήσεις.",
        uiRequiredWebMapSetup: "⚙️ Απαιτούμενη ρύθμιση χάρτη ιστού",
        uiTheCommentsSurveysAndPhotosTables: "Τα σχόλια, έρευνες, και φωτογραφίες πίνακες πρέπει να είναι",
        uiExplicitlyAddedToYourWebMap: "ρητά προστίθενται στο web map σας",
        uiInPortalMapViewerPublishingThe: "στο Portal Map Viewer — η δημοσίευση του FeatureServer από μόνη της δεν αρκεί.",
        uiOpenYourWebMapInPortal: "Άνοιγμα του χάρτη σας στο Portal Map Viewer",
        uiAddLayerBrowseTo: "Προσθήκη στρώματος → περιήγηση σε",
        uiReportaconcernManagerFeatureserver: "ΑναφοράAConcern Manager / FeatureServer",
        uiAddEachOfTheseAs: "Προσθέστε κάθε ένα από αυτά ως",
        uiTables: "Πίνακες",
        uiNotLayers: "(όχι στρώματα):",
        uiTicketComments: "Εισιτήριο Comment",
        uiSurveyResponses: "Έρευνα Απαντήσεις",
        uiTicketPhotosMeta: "Εισιτήριο Φωτογραφίες Μέτα",
        uiSaveTheWebMap: "Αποθήκευση του χάρτη ιστού",
        uiToVerify: "Για επαλήθευση:",
        uiOpenTheBrowserConsoleAfterThe: "Άνοιγμα της κονσόλας περιηγητή μετά τα φορτία widget και αναζήτηση γραμμών ξεκινώντας με",
        uiRacManager: "Διαχειριστής RAC:",
        uiNotFound: "Δεν βρέθηκε",
        uiThatTableIsMissingFromThe: "Το τραπέζι λείπει από το χάρτη.",
        uiAllAuthFlowsThroughThePortal: "Όλες οι ωοθήκες περνούν από τη συνεδρία της Πύλης — δεν χρειάζονται επιπλέον μάρκες. Για να περιοριστεί η πρόσβαση, μοιραστείτε την εφαρμογή με μια ομάδα Portal.",
        tickets: "Εισιτήρια",
        eachTableShouldShowItsTitle: ". Each table should show its title — if any say"
      })
    }
  }
})
