/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        uiRacManagerSettings: "Configuración de RAC Manager",
        uiMapWidget: "Mapa widget",
        uiSelectTheMapThatContainsYour: "Seleccione el mapa que contiene sus capas de servicio de características RAC.",
        uiTicketsLayerTitle: "Título de la capa de entradas",
        uiMustMatchTheLayerTitleExactly: "Debe coincidir con el título de capa exactamente como aparece en el mapa web.",
        uiCommentsTableName: "Nombre de la tabla",
        uiTokenBasedMatchUnderscoresAndSpaces: "Coincidencia basada en tokens: los subrayados y los espacios se tratan de la misma manera (caso insensible).",
        uiPhotosTableName: "Cuadro Nombre",
        uiSurveyTableName: "Nombre del cuadro",
        uiOrganizationName: "Nombre de la Organización",
        uiShownAsTheAuthorAndSubtitle: "Muestra como autor y subtítulo de la exportación de Excel.",
        uiHelpButtonAndGuide: "Ayuda botón y guía",
        uiShowTheHelpButtonAndThe: "Mostrar el botón Ayuda y la pista de primera ejecución",
        uiShowsAHelpButtonAtThe: "Muestra un botón Ayuda en la parte superior derecha del widget y una pista única para nuevos usuarios. Apágalo para el quiosco o usos incrustados.",
        uiRequiredWebMapSetup: "Configuración de mapas web obligatorios",
        uiTheCommentsSurveysAndPhotosTables: "Los comentarios, encuestas y tablas de fotos deben ser",
        uiExplicitlyAddedToYourWebMap: "explícitamente añadido a su mapa web",
        uiInPortalMapViewerPublishingThe: "en Portal Map Viewer — publicar el FeatureServer solo no es suficiente.",
        uiOpenYourWebMapInPortal: "Abra su mapa web en Portal Map Viewer",
        uiAddLayerBrowseTo: "Añadir capa → navegar",
        uiReportaconcernManagerFeatureserver: "ReportAConcern Manager / CaracterísticaServer",
        uiAddEachOfTheseAs: "Añadir cada uno de estos",
        uiTables: "Tablas",
        uiNotLayers: "(no capas):",
        uiTicketComments: "Ticket Comentarios",
        uiSurveyResponses: "Survey Responses",
        uiTicketPhotosMeta: "Ticket Photos Meta",
        uiSaveTheWebMap: "Guardar el mapa web",
        uiToVerify: "Para verificar:",
        uiOpenTheBrowserConsoleAfterThe: "Abra la consola del navegador después de las cargas del widget y busque líneas comenzando con",
        uiRacManager: "RAC Manager:",
        uiNotFound: "NO FONDO",
        uiThatTableIsMissingFromThe: ", esa tabla falta del mapa web.",
        uiAllAuthFlowsThroughThePortal: "Todas las corrientes de austeridad a través de la sesión del Portal — no se necesitan fichas adicionales. Para restringir el acceso, comparta la aplicación con un grupo Portal.",
        tickets: "Billetes",
        eachTableShouldShowItsTitle: ". Each table should show its title — if any say"
      })
    }
  }
})
