/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        uiRacManagerSettings: "RAC- i halduri seadistused",
        uiMapWidget: "Kaardividina",
        uiSelectTheMapThatContainsYour: "Valige kaart, mis sisaldab teie RAC-funktsiooni teenusekihte.",
        uiTicketsLayerTitle: "Piletikihi tiitel",
        uiMustMatchTheLayerTitleExactly: "Kihi pealkiri peab sobima täpselt nii, nagu see on veebikaardil.",
        uiCommentsTableName: "Märkused Tabeli nimi",
        uiTokenBasedMatchUnderscoresAndSpaces: "Token-põhine vaste – alakriipsu ja tühikuid käsitletakse samamoodi (juhutundlik).",
        uiPhotosTableName: "Fotod Tabeli nimi",
        uiSurveyTableName: "Uuringu tabeli nimi",
        uiOrganizationName: "Organisatsiooni nimi",
        uiShownAsTheAuthorAndSubtitle: "Näidatud kui Exceli ekspordi autor ja subtiiter.",
        uiHelpButtonAndGuide: "Abinupp ja juhend",
        uiShowTheHelpButtonAndThe: "Nuppu Abi ja esimese käigu vihje näitamine",
        uiShowsAHelpButtonAtThe: "Näitab vidina üleval paremal asuvat nuppu Abi ja ühekordset vihjet uutele kasutajatele. Lülita see välja kioski või põimitud kasutuse korral.",
        uiRequiredWebMapSetup: "️️ Nõutav veebikaardi seadistamine",
        uiTheCommentsSurveysAndPhotosTables: "Kommentaarid, küsitlused ja fotod peavad olema",
        uiExplicitlyAddedToYourWebMap: "selgesõnaliselt lisatud teie veebikaardile",
        uiInPortalMapViewerPublishingThe: "Portaali kaardivaatajas – funktsiooniserveri avaldamisest üksi ei piisa.",
        uiOpenYourWebMapInPortal: "Ava oma veebikaart portaalikaardi näitajas",
        uiAddLayerBrowseTo: "Lisa kiht → sirvimine",
        uiReportaconcernManagerFeatureserver: "ReportAConcern Manager / FeatureServer",
        uiAddEachOfTheseAs: "Lisage kõik need",
        uiTables: "Tabelid",
        uiNotLayers: "(mitte kihid):",
        uiTicketComments: "Pileti Kommentaarid",
        uiSurveyResponses: "Uuring vastused",
        uiTicketPhotosMeta: "Pilet Fotod Meta",
        uiSaveTheWebMap: "Salvesta veebikaart",
        uiToVerify: "Et kontrollida:",
        uiOpenTheBrowserConsoleAfterThe: "Avage brauseri konsool pärast vidina laadimist ja otsige ridu, mis algavad",
        uiRacManager: "PNK juht:",
        uiNotFound: "Ei leitud",
        uiThatTableIsMissingFromThe: ", see tabel puudub veebikaardilt.",
        uiAllAuthFlowsThroughThePortal: "Kogu autentimine voolab läbi Portaali seansi – lisamärke pole vaja. Juurdepääsu piiramiseks jagage rakendust portaali rühmaga.",
        tickets: "Piletid",
        eachTableShouldShowItsTitle: ". Each table should show its title — if any say"
      })
    }
  }
})
