/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        uiRacManagerSettings: "Toimikuntien johdon asetukset",
        uiMapWidget: "Karttaelementti",
        uiSelectTheMapThatContainsYour: "Valitse kartta, joka sisältää RAC ominaisuus palvelun kerroksia.",
        uiTicketsLayerTitle: "Liput Layer Otsikko",
        uiMustMatchTheLayerTitleExactly: "Täytyy täsmätä kerroksen otsikko juuri kuin se näkyy web-kartassa.",
        uiCommentsTableName: "Huomautukset Taulukon nimi",
        uiTokenBasedMatchUnderscoresAndSpaces: "Token-pohjainen ottelu",
        uiPhotosTableName: "Kuvat Taulukon nimi",
        uiSurveyTableName: "Tutkimustaulukon nimi",
        uiOrganizationName: "Organisaation nimi",
        uiShownAsTheAuthorAndSubtitle: "Näytetään Excel-viennin kirjoittajana ja tekstityksenä.",
        uiHelpButtonAndGuide: "Ohjepainike ja opas",
        uiShowTheHelpButtonAndThe: "Näytä Ohje-painike ja ensimmäisen kierroksen vihje",
        uiShowsAHelpButtonAtThe: "Näyttää Ohje-painikkeen oikeassa yläreunassa widget ja yhden kerran vihje uusille käyttäjille. Sammuta se kioskia tai sulautettuja käyttötarkoituksia varten.",
        uiRequiredWebMapSetup: "⚙️ Required Web Map Setup",
        uiTheCommentsSurveysAndPhotosTables: "Kommentit, tutkimukset ja kuvat taulukoita on oltava",
        uiExplicitlyAddedToYourWebMap: "nimenomaisesti lisätty web-kartallesi",
        uiInPortalMapViewerPublishingThe: "Portal Map Viewer ... julkaisussa FeatureServer yksin ei riitä.",
        uiOpenYourWebMapInPortal: "Avaa verkkokarttasi Portal Map Viewer",
        uiAddLayerBrowseTo: "Lisää kerros → selaa",
        uiReportaconcernManagerFeatureserver: "ReportAConcern Manager / FeatureServer",
        uiAddEachOfTheseAs: "Lisää jokainen näistä",
        uiTables: "Taulut",
        uiNotLayers: "(ei kerroksia):",
        uiTicketComments: "Lippukommentit",
        uiSurveyResponses: "Kysely vastaukset",
        uiTicketPhotosMeta: "Lippu Kuva Meta",
        uiSaveTheWebMap: "Tallenna web-kartta",
        uiToVerify: "Varmistetaan:",
        uiOpenTheBrowserConsoleAfterThe: "Avaa selaimen konsoli jälkeen widget kuormia ja etsiä riviä alkaen",
        uiRacManager: "RAC:n johtaja:",
        uiNotFound: "Ei löytynyt.",
        uiThatTableIsMissingFromThe: "Tuo pöytä puuttuu nettikartasta.",
        uiAllAuthFlowsThroughThePortal: "Kaikki auth virtaa läpi portaalin istunnon . Ei ylimääräisiä kuponkia tarvitaan. Rajoittaaksesi pääsyä, jaa sovellus portaaliryhmän kanssa.",
        tickets: "Liput",
        eachTableShouldShowItsTitle: ". Each table should show its title — if any say"
      })
    }
  }
})
