/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        uiRacManagerSettings: "Paramètres du gestionnaire RAC",
        uiMapWidget: "Widget de carte",
        uiSelectTheMapThatContainsYour: "Sélectionnez la carte qui contient vos couches de service RAC.",
        uiTicketsLayerTitle: "Titre du calque des billets",
        uiMustMatchTheLayerTitleExactly: "Doit correspondre exactement au titre du calque tel qu'il apparaît sur la carte web.",
        uiCommentsTableName: "Commentaires Nom du tableau",
        uiTokenBasedMatchUnderscoresAndSpaces: "Match à base de jetons — les accents et les espaces sont traités de la même manière (insensible au cas par cas).",
        uiPhotosTableName: "Photos Nom du tableau",
        uiSurveyTableName: "Nom du tableau d'enquête",
        uiOrganizationName: "Nom de l'organisation",
        uiShownAsTheAuthorAndSubtitle: "Montré comme auteur et sous-titre de l'export Excel.",
        uiHelpButtonAndGuide: "Bouton d'aide et guide",
        uiShowTheHelpButtonAndThe: "Afficher le bouton Aide et l'indice de première sortie",
        uiShowsAHelpButtonAtThe: "Affiche un bouton Aide en haut à droite du widget et un indice unique pour les nouveaux utilisateurs. Éteignez-le pour les kiosques ou les applications intégrées.",
        uiRequiredWebMapSetup: "Configuration requise de la carte Web",
        uiTheCommentsSurveysAndPhotosTables: "Les tableaux Commentaires, Enquêtes et Photos doivent être",
        uiExplicitlyAddedToYourWebMap: "explicitement ajouté à votre carte web",
        uiInPortalMapViewerPublishingThe: "dans Portal Map Viewer — publier le FeatureServer seul ne suffit pas.",
        uiOpenYourWebMapInPortal: "Ouvrez votre carte web dans Portal Map Viewer",
        uiAddLayerBrowseTo: "Ajouter un calque →",
        uiReportaconcernManagerFeatureserver: "ReportAConcern Manager / FeatureServer",
        uiAddEachOfTheseAs: "Ajouter chacun de ces éléments",
        uiTables: "Tables",
        uiNotLayers: "(pas de couches):",
        uiTicketComments: "Commentaires sur les billets",
        uiSurveyResponses: "Enquête réponses",
        uiTicketPhotosMeta: "Ticket Photos Meta",
        uiSaveTheWebMap: "Enregistrer la carte web",
        uiToVerify: "Pour vérifier :",
        uiOpenTheBrowserConsoleAfterThe: "Ouvrez la console du navigateur après le widget charge et recherchez des lignes commençant par",
        uiRacManager: "Gestionnaire du CCR :",
        uiNotFound: "PAS FOND",
        uiThatTableIsMissingFromThe: ", cette table est absente de la carte web.",
        uiAllAuthFlowsThroughThePortal: "Toutes les autorisations transitent par la session du Portail — aucun jeton supplémentaire n'est nécessaire. Pour restreindre l'accès, partagez l'application avec un groupe Portal.",
        tickets: "Billets",
        eachTableShouldShowItsTitle: ". Each table should show its title — if any say"
      })
    }
  }
})
