/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        uiRacManagerSettings: "RAC Manager Settings",
        uiMapWidget: "מפה widget",
        uiSelectTheMapThatContainsYour: "Select the map that contains your RAC feature service layers.",
        uiTicketsLayerTitle: "Tickets Layer Title",
        uiMustMatchTheLayerTitleExactly: "Must match the layer title exactly as it appears in the web map.",
        uiCommentsTableName: "Comments Table Name",
        uiTokenBasedMatchUnderscoresAndSpaces: "Token-based match — underscores and spaces are treated the same (case-insensitive).",
        uiPhotosTableName: "Photos Table Name",
        uiSurveyTableName: "Survey Table Name",
        uiOrganizationName: "Organization Name",
        uiShownAsTheAuthorAndSubtitle: "Shown as the author and subtitle of the Excel export.",
        uiHelpButtonAndGuide: "Help button and guide",
        uiShowTheHelpButtonAndThe: "Show the Help button and the first-run hint",
        uiShowsAHelpButtonAtThe: "Shows a Help button at the top right of the widget and a one-time hint for new users. Turn it off for kiosk or embedded uses.",
        uiRequiredWebMapSetup: "⚙️ Required Web Map Setup",
        uiTheCommentsSurveysAndPhotosTables: "The Comments, Surveys, and Photos tables must be",
        uiExplicitlyAddedToYourWebMap: "explicitly added to your web map",
        uiInPortalMapViewerPublishingThe: "in Portal Map Viewer — publishing the FeatureServer alone is not enough.",
        uiOpenYourWebMapInPortal: "Open your web map in Portal Map Viewer",
        uiAddLayerBrowseTo: "Add layer → browse to",
        uiReportaconcernManagerFeatureserver: "ReportAConcern_Manager / FeatureServer",
        uiAddEachOfTheseAs: "Add each of these as",
        uiTables: "טבלאות",
        uiNotLayers: "(not layers):",
        uiTicketComments: "Ticket_Comments",
        uiSurveyResponses: "Survey_Responses",
        uiTicketPhotosMeta: "Ticket_Photos_Meta",
        uiSaveTheWebMap: "Save the web map",
        uiToVerify: "To verify:",
        uiOpenTheBrowserConsoleAfterThe: "Open the browser console after the widget loads and look for lines starting with",
        uiRacManager: "RAC Manager:",
        uiNotFound: "NOT FOUND",
        uiThatTableIsMissingFromThe: ", that table is missing from the web map.",
        uiAllAuthFlowsThroughThePortal: "All auth flows through the Portal session — no extra tokens needed. To restrict access, share the app with a Portal group.",
        tickets: "Tickets"
      })
    }
  }
})
