/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        uiRacManagerSettings: "הגדרות מנהל RAC",
        uiMapWidget: "מפה widget",
        uiSelectTheMapThatContainsYour: "בחר את המפה המכילה את שכבות השירות של RAC שלך.",
        uiTicketsLayerTitle: "כרטיסים ל Layer",
        uiMustMatchTheLayerTitleExactly: "חייב להתאים את שם השכבה בדיוק כפי שהוא מופיע במפה.",
        uiCommentsTableName: "שם השולחן",
        uiTokenBasedMatchUnderscoresAndSpaces: "משחק מבוסס Token - מדגישים ומרחבים מטופלים זהה (רגישים).",
        uiPhotosTableName: "שם שולחן תמונות",
        uiSurveyTableName: "שם מקור: Table Name",
        uiOrganizationName: "שם הארגון",
        uiShownAsTheAuthorAndSubtitle: "מוצג כמחבר וכותרת של ייצוא Excel.",
        uiHelpButtonAndGuide: "עזרה בלחיצת כפתור ומדריך",
        uiShowTheHelpButtonAndThe: "הצג את כפתור העזרה ואת הרמז הראשון",
        uiShowsAHelpButtonAtThe: "מציג כפתור עזרה בצד העליון של widget ורמז חד פעמי למשתמשים חדשים. הפעל אותו לשימושי קיוסק או מוטבע.",
        uiRequiredWebMapSetup: "דרישות Web Map",
        uiTheCommentsSurveysAndPhotosTables: "הערות, סקרים וטבלאות תמונות חייב להיות",
        uiExplicitlyAddedToYourWebMap: "הוסף במפורש למפת האינטרנט שלך",
        uiInPortalMapViewerPublishingThe: "ב-Portal Map Viewer - פרסום ה-PowerServer לבדו אינו מספיק.",
        uiOpenYourWebMapInPortal: "פתח את מפת האינטרנט שלך בפורטל Viewer",
        uiAddLayerBrowseTo: "הוסף שכבה",
        uiReportaconcernManagerFeatureserver: "דיווח AConcern Manager / FeatureServer",
        uiAddEachOfTheseAs: "הוסף כל אחד מאלה",
        uiTables: "טבלאות",
        uiNotLayers: "(לא שכבות):",
        uiTicketComments: "כרטיסים Comments",
        uiSurveyResponses: "תוצאות חיפוש >Responses",
        uiTicketPhotosMeta: "כרטיסים Photos Meta",
        uiSaveTheWebMap: "שמור את מפת האינטרנט",
        uiToVerify: "לאמת:",
        uiOpenTheBrowserConsoleAfterThe: "פתח את קונסולת הדפדפן לאחר עומסי widget וחפש קווים החל עם",
        uiRacManager: "מנהל RAC:",
        uiNotFound: "לא FOUND",
        uiThatTableIsMissingFromThe: "השולחן חסר ממפת האינטרנט.",
        uiAllAuthFlowsThroughThePortal: "כל האתחול זורם דרך מושב השער - אין צורך בסימון נוסף. כדי להגביל גישה, לשתף את האפליקציה עם קבוצת פורטל.",
        tickets: "כרטיסים",
        eachTableShouldShowItsTitle: ". Each table should show its title — if any say"
      })
    }
  }
})
