/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        uiRacManagerSettings: "RAC kezelőbeállítások",
        uiMapWidget: "Térképek",
        uiSelectTheMapThatContainsYour: "Válassza ki a RAC szolgáltatás rétegeit tartalmazó térképet.",
        uiTicketsLayerTitle: "Jegyek réteg címe",
        uiMustMatchTheLayerTitleExactly: "Meg kell egyeznie a réteg cím pontosan úgy, ahogy megjelenik a web térképen.",
        uiCommentsTableName: "Megjegyzések Táblázat neve",
        uiTokenBasedMatchUnderscoresAndSpaces: "Token- alapú mérkőzés - alulvonások és szóközök kezelik ugyanaz (esetérzéketlen).",
        uiPhotosTableName: "Fotók táblázatneve",
        uiSurveyTableName: "táblázat",
        uiOrganizationName: "A szervezet neve",
        uiShownAsTheAuthorAndSubtitle: "Az Excel export szerzője és alcíme.",
        uiHelpButtonAndGuide: "Súgó gomb és útmutató",
        uiShowTheHelpButtonAndThe: "Megjeleníti a Súgó gombot és az első futási tippet",
        uiShowsAHelpButtonAtThe: "Megjelenít egy Súgó gombot a widget jobb felső sarkában és egy egyszeri tippet az új felhasználóknak. Kapcsold ki kioszk vagy beágyazott használatra.",
        uiRequiredWebMapSetup: "A webes térkép beállítása",
        uiTheCommentsSurveysAndPhotosTables: "A Comments, Survey, és Fotók asztalok kell lennie",
        uiExplicitlyAddedToYourWebMap: "kifejezetten hozzá a webes térkép",
        uiInPortalMapViewerPublishingThe: "a Portal Térkép Viewer - kiadás a FeatureServer önmagában nem elég.",
        uiOpenYourWebMapInPortal: "A webes térkép megnyitása portálon Térkép Megtekintése",
        uiAddLayerBrowseTo: "Hozzáadás réteg → böngészés",
        uiReportaconcernManagerFeatureserver: "ReportaConcern _ Manager / FeatureServer",
        uiAddEachOfTheseAs: "Mindegyikkel egészítendő ki:",
        uiTables: "Táblázatok",
        uiNotLayers: "(nem rétegek):",
        uiTicketComments: "Ticket _ Comments",
        uiSurveyResponses: "Survey _ Responses",
        uiTicketPhotosMeta: "Ticket _ Photos _ Meta",
        uiSaveTheWebMap: "A webes térkép mentése",
        uiToVerify: "A következők ellenőrzése:",
        uiOpenTheBrowserConsoleAfterThe: "A widget betöltése után nyissa meg a böngésző konzolt, és keresse meg a sorokat kezdve a",
        uiRacManager: "RAC Manager:",
        uiNotFound: "NEM TALÁLHATÓ",
        uiThatTableIsMissingFromThe: "Az az asztal hiányzik a webtérképről.",
        uiAllAuthFlowsThroughThePortal: "Minden audio átfolyik a portálon - nincs szükség extra zsetonra. A hozzáférés korlátozásához ossza meg az alkalmazást egy portálcsoporttal.",
        tickets: "Jegyek",
        eachTableShouldShowItsTitle: ". Each table should show its title — if any say"
      })
    }
  }
})
