/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        uiRacManagerSettings: "Pengaturan Manajer RAC",
        uiMapWidget: "Widget peta",
        uiSelectTheMapThatContainsYour: "Pilih peta yang memuat lapisan layanan fitur RAC Anda.",
        uiTicketsLayerTitle: "Judul Lapis Tiket",
        uiMustMatchTheLayerTitleExactly: "Harus sesuai judul lapisan persis seperti yang muncul dalam peta web.",
        uiCommentsTableName: "Nama Tabel Komentar",
        uiTokenBasedMatchUnderscoresAndSpaces: "Token-based match - garis-bawah dan spasi diperlakukan sama (case- sensitivitas).",
        uiPhotosTableName: "Nama Tabel Foto",
        uiSurveyTableName: "Nama Tabel Survey",
        uiOrganizationName: "Nama Organisasi",
        uiShownAsTheAuthorAndSubtitle: "Shown sebagai penulis dan subjudul ekspor Excel.",
        uiHelpButtonAndGuide: "Tombol bantuan dan pemandu",
        uiShowTheHelpButtonAndThe: "Tampilkan tombol Bantuan dan petunjuk first-run",
        uiShowsAHelpButtonAtThe: "Tampilkan tombol Bantuan di kanan atas widget dan petunjuk satu kali bagi pengguna baru. Matikan untuk kios atau gunakan tertanam.",
        uiRequiredWebMapSetup: "Penyiapan Peta Web yang Diperlukan",
        uiTheCommentsSurveysAndPhotosTables: "Komentar, penelitian, dan tabel foto harus",
        uiExplicitlyAddedToYourWebMap: "secara eksplisit ditambahkan ke peta web Anda",
        uiInPortalMapViewerPublishingThe: "dalam Penilik Peta Portal - menerbitkan FeatureServer saja tidak cukup.",
        uiOpenYourWebMapInPortal: "Buka peta web Anda dalam Penilik Peta Portal",
        uiAddLayerBrowseTo: "undo-type",
        uiReportaconcernManagerFeatureserver: "ReportAConcern _ Manager / FeatureServer",
        uiAddEachOfTheseAs: "Tambahkan masing-masing sebagai",
        uiTables: "Tabel",
        uiNotLayers: "(bukan lapis):",
        uiTicketComments: "_ Komentar Tiket",
        uiSurveyResponses: "_ Respon Survey",
        uiTicketPhotosMeta: "_ Tiket Foto Meta",
        uiSaveTheWebMap: "Simpan peta web",
        uiToVerify: "Untuk memverifikasi:",
        uiOpenTheBrowserConsoleAfterThe: "Buka konsol peramban setelah beban widget dan cari baris yang dimulai dengan",
        uiRacManager: "Manajer RAC:",
        uiNotFound: "TIDAK DITEMUKAN",
        uiThatTableIsMissingFromThe: ", meja yang hilang dari peta web.",
        uiAllAuthFlowsThroughThePortal: "Semua auth mengalir melalui sesi Portal - tidak ada token tambahan yang diperlukan. Untuk membatasi akses, berbagi aplikasi dengan grup Portal.",
        tickets: "Tiket",
        eachTableShouldShowItsTitle: ". Each table should show its title — if any say"
      })
    }
  }
})
