/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        uiRacManagerSettings: "Impostazioni Gestione RAC",
        uiMapWidget: "Mappa widget",
        uiSelectTheMapThatContainsYour: "Seleziona la mappa che contiene gli strati di servizio della funzione RAC.",
        uiTicketsLayerTitle: "Titolo dei biglietti",
        uiMustMatchTheLayerTitleExactly: "Deve corrispondere il titolo dello strato esattamente come appare nella mappa web.",
        uiCommentsTableName: "Nome della tabella",
        uiTokenBasedMatchUnderscoresAndSpaces: "La partita a base di token — i segni e gli spazi sono trattati lo stesso (caso-insensibile).",
        uiPhotosTableName: "Nome della tabella delle foto",
        uiSurveyTableName: "Nome della tabella di indagine",
        uiOrganizationName: "Nome dell'organizzazione",
        uiShownAsTheAuthorAndSubtitle: "Mostrato come l'autore e sottotitolo dell'esportazione di Excel.",
        uiHelpButtonAndGuide: "Pulsante e guida",
        uiShowTheHelpButtonAndThe: "Mostra il pulsante Aiuto e il suggerimento di prima corsa",
        uiShowsAHelpButtonAtThe: "Mostra un pulsante Aiuto in alto a destra del widget e un suggerimento una volta per nuovi utenti. Spegnilo per chiosco o usi incorporati.",
        uiRequiredWebMapSetup: "⚙️ Impostazione della mappa web richiesta",
        uiTheCommentsSurveysAndPhotosTables: "I commenti, i sondaggi e le tabelle foto devono essere",
        uiExplicitlyAddedToYourWebMap: "esplicitamente aggiunto alla tua mappa web",
        uiInPortalMapViewerPublishingThe: "in Portal Map Viewer — pubblicare il FeatureServer da solo non è sufficiente.",
        uiOpenYourWebMapInPortal: "Apri la tua mappa web in Portal Map Viewer",
        uiAddLayerBrowseTo: "Aggiungere strato → sfogliare",
        uiReportaconcernManagerFeatureserver: "ReportAConcern Manager / FeatureServer",
        uiAddEachOfTheseAs: "Aggiungere ciascuno di questi come",
        uiTables: "Tabelle",
        uiNotLayers: "(non strati):",
        uiTicketComments: "Biglietto Commenti",
        uiSurveyResponses: "Indagine Risponsabilità",
        uiTicketPhotosMeta: "Biglietto Foto Meta",
        uiSaveTheWebMap: "Salvare la mappa web",
        uiToVerify: "Per verificare:",
        uiOpenTheBrowserConsoleAfterThe: "Aprire la console del browser dopo i carichi del widget e cercare le linee che iniziano con",
        uiRacManager: "Direttore RAC:",
        uiNotFound: "Non è vero.",
        uiThatTableIsMissingFromThe: ", quel tavolo manca dalla mappa web.",
        uiAllAuthFlowsThroughThePortal: "Tutti i flussi auth attraverso la sessione Portal — nessun gettoni extra necessari. Per limitare l'accesso, condividere l'app con un gruppo Portal.",
        tickets: "Biglietti",
        eachTableShouldShowItsTitle: ". Each table should show its title — if any say"
      })
    }
  }
})
