/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        uiRacManagerSettings: "RAC マネージャの設定",
        uiMapWidget: "地図ウィジェット",
        uiSelectTheMapThatContainsYour: "RAC機能のサービスレイヤーを含むマップを選択します。",
        uiTicketsLayerTitle: "チケット層のタイトル",
        uiMustMatchTheLayerTitleExactly: "Webマップに表示されるようにレイヤーのタイトルを正確に一致する必要があります。",
        uiCommentsTableName: "コメントテーブル名",
        uiTokenBasedMatchUnderscoresAndSpaces: "トークンベースのマッチ — アンダースコアとスペースは同じ(ケースインセンティブ)で処理されます。",
        uiPhotosTableName: "写真のテーブルの名前",
        uiSurveyTableName: "調査テーブル名",
        uiOrganizationName: "組織名称",
        uiShownAsTheAuthorAndSubtitle: "Excelエクスポートの著者とサブタイトルとして表示します。",
        uiHelpButtonAndGuide: "ヘルプボタンとガイド",
        uiShowTheHelpButtonAndThe: "ヘルプボタンと最初のヒントを表示する",
        uiShowsAHelpButtonAtThe: "ウィジェットの右上にあるヘルプボタンと、新しいユーザーのワンタイムヒントを表示します。 キオスクや埋め込み用途でオフにします。",
        uiRequiredWebMapSetup: "◀️ 必要なWebマップのセットアップ",
        uiTheCommentsSurveysAndPhotosTables: "コメント、調査、写真表は必須です。",
        uiExplicitlyAddedToYourWebMap: "ウェブマップに明示的に追加",
        uiInPortalMapViewerPublishingThe: "ポータルマップビューア — FeatureServer を単独で公開するのは十分ではありません。",
        uiOpenYourWebMapInPortal: "ポータルマップビューアでWebマップを開く",
        uiAddLayerBrowseTo: "レイヤーを追加 → 参照する",
        uiReportaconcernManagerFeatureserver: "ReportAConcern Manager/機能サーバ",
        uiAddEachOfTheseAs: "これらをそれぞれ追加する",
        uiTables: "テーブル",
        uiNotLayers: "(層ではない):",
        uiTicketComments: "チケット コメント",
        uiSurveyResponses: "アンケート 回答",
        uiTicketPhotosMeta: "チケット 写真 メタ",
        uiSaveTheWebMap: "サイトマップ",
        uiToVerify: "確認のため:",
        uiOpenTheBrowserConsoleAfterThe: "ウィジェットがロードした後、ブラウザコンソールを開き、先頭から行を探します",
        uiRacManager: "RAC マネージャー:",
        uiNotFound: "禁止事項",
        uiThatTableIsMissingFromThe: ", この表はウェブマップから欠落しています。",
        uiAllAuthFlowsThroughThePortal: "すべてのauthはポータルセッションを通して流れます。追加のトークンは必要ありません。 アクセスを制限するには、ポータルグループでアプリを共有します。",
        tickets: "チケット",
        eachTableShouldShowItsTitle: ". Each table should show its title — if any say"
      })
    }
  }
})
