/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        uiRacManagerSettings: "RAC 관리자 설정",
        uiMapWidget: "지도 위젯",
        uiSelectTheMapThatContainsYour: "RAC 기능 서비스 레이어를 포함하는지도를 선택하십시오.",
        uiTicketsLayerTitle: "표 층 제목",
        uiMustMatchTheLayerTitleExactly: "웹 맵에 나타나는 것처럼 레이어 제목을 정확히 일치해야합니다.",
        uiCommentsTableName: "댓글 표 이름",
        uiTokenBasedMatchUnderscoresAndSpaces: "Token-based match — underscores 및 공백은 동일하게 대우됩니다 (case-insensitive).",
        uiPhotosTableName: "사진 테이블 이름",
        uiSurveyTableName: "조사 테이블 이름",
        uiOrganizationName: "회사명",
        uiShownAsTheAuthorAndSubtitle: "Excel 수출의 저자 및 자막으로 표시됩니다.",
        uiHelpButtonAndGuide: "도움말 버튼 및 가이드",
        uiShowTheHelpButtonAndThe: "도움말 버튼과 첫 번째 실행 힌트 표시",
        uiShowsAHelpButtonAtThe: "위젯의 오른쪽 상단에 도움말 버튼을 표시하고 새로운 사용자를위한 한 번 힌트. kiosk 또는 임베디드 용도에 대해 끄십시오.",
        uiRequiredWebMapSetup: "ܧ️ 필수 웹 맵 설정",
        uiTheCommentsSurveysAndPhotosTables: "댓글, 설문 조사 및 사진 테이블이 있어야합니다.",
        uiExplicitlyAddedToYourWebMap: "웹 맵에 명시된 추가",
        uiInPortalMapViewerPublishingThe: "Portal Map Viewer에서 - FeatureServer를 단독으로 게시하는 것은 충분하지 않습니다.",
        uiOpenYourWebMapInPortal: "Portal Map Viewer의 웹 맵 열기",
        uiAddLayerBrowseTo: "레이어 추가 → 검색",
        uiReportaconcernManagerFeatureserver: "ReportAConcern Manager / 기능서버",
        uiAddEachOfTheseAs: "이들의 각각을",
        uiTables: "테이블",
        uiNotLayers: "(층이 아닙니다):",
        uiTicketComments: "티켓 예약",
        uiSurveyResponses: "Survey 책임",
        uiTicketPhotosMeta: "티켓 Photos Meta",
        uiSaveTheWebMap: "웹 맵 저장",
        uiToVerify: "인증:",
        uiOpenTheBrowserConsoleAfterThe: "위젯로드 후 브라우저 콘솔을 열고 줄을 찾습니다.",
        uiRacManager: "RAC 매니저:",
        uiNotFound: "공지사항",
        uiThatTableIsMissingFromThe: ", 그 테이블은 웹지도에서 누락.",
        uiAllAuthFlowsThroughThePortal: "모든 auth는 포털 세션을 통해 흐릅니다 - 추가 토큰이 필요하지 않습니다. 액세스 제한, 포털 그룹과 앱 공유.",
        tickets: "상품정보",
        eachTableShouldShowItsTitle: ". Each table should show its title — if any say"
      })
    }
  }
})
