/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        uiRacManagerSettings: "RAC tvarkyklės nustatymai",
        uiMapWidget: "Žemėlapio valdiklis",
        uiSelectTheMapThatContainsYour: "Pasirinkite žemėlapį, kuriame yra RPT funkcijų paslaugų sluoksniai.",
        uiTicketsLayerTitle: "Bilietų sluoksnio pavadinimas",
        uiMustMatchTheLayerTitleExactly: "NAME OF TRANSLATORS",
        uiCommentsTableName: "Pastabos Lentelės pavadinimas",
        uiTokenBasedMatchUnderscoresAndSpaces: "Tokinų pagrindu nustatytos rungtynės - pabraukimai ir tarpai yra traktuojami vienodai (nejautrus).",
        uiPhotosTableName: "Nuotraukų lentelės pavadinimas",
        uiSurveyTableName: "Tyrimo lentelės pavadinimas",
        uiOrganizationName: "Organizacijos pavadinimas",
        uiShownAsTheAuthorAndSubtitle: "Rodyti kaip autorius ir paantraštės Excel eksporto.",
        uiHelpButtonAndGuide: "Žinynas ir žinynas",
        uiShowTheHelpButtonAndThe: "Rodyti pagalbos mygtuką ir pirmąją užuominą",
        uiShowsAHelpButtonAtThe: "Rodo pagalbos mygtuką viršuje dešinėje valdikliui ir vieną kartą užuominą naujiems vartotojams. Išjunkite jį kioskas arba įterptųjų.",
        uiRequiredWebMapSetup: "® Reikiamas žiniatinklio žemėlapio nustatymų rinkinys",
        uiTheCommentsSurveysAndPhotosTables: "Pastabos, apklausos, ir nuotraukos lentelės turi būti",
        uiExplicitlyAddedToYourWebMap: "aiškiai pridėta į savo interneto žemėlapį",
        uiInPortalMapViewerPublishingThe: "Portale Žemėlapis žiūryklė - leidybos vien FeatureServer nepakanka.",
        uiOpenYourWebMapInPortal: "Atsidarykite žiniatinklio žemėlapį Portale Žemėlapis žiūryklė",
        uiAddLayerBrowseTo: "Pridėti sluoksnį → naršyti",
        uiReportaconcernManagerFeatureserver: "reportAConcern _ Manager / FeatureServer",
        uiAddEachOfTheseAs: "Pridėti kiekvieną iš šių:",
        uiTables: "Lentelės",
        uiNotLayers: "(ne sluoksniais):",
        uiTicketComments: "Bilieto _ komentarai",
        uiSurveyResponses: "_ Survey atsakymai",
        uiTicketPhotosMeta: "Bilietas _ Nuotraukos _ Meta",
        uiSaveTheWebMap: "Įrašyti žiniatinklio žemėlapį",
        uiToVerify: "Patikrinti:",
        uiOpenTheBrowserConsoleAfterThe: "@ info: whatsthis",
        uiRacManager: "RPT vadovas:",
        uiNotFound: "NETAIKOMA",
        uiThatTableIsMissingFromThe: ", kad lentelė trūksta iš interneto žemėlapyje.",
        uiAllAuthFlowsThroughThePortal: "All auth teka per portalo sesiją - nereikia jokių papildomų žetonų. NAME OF TRANSLATORS",
        tickets: "Bilietai",
        eachTableShouldShowItsTitle: ". Each table should show its title — if any say"
      })
    }
  }
})
