/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        uiRacManagerSettings: "RAC pārvaldnieka iestatījumi",
        uiMapWidget: "Kartes sīkrīks",
        uiSelectTheMapThatContainsYour: "Izvēlieties karti, kas satur jūsu RAC funkciju servisa slāņus.",
        uiTicketsLayerTitle: "Biļetes Nosaukums",
        uiMustMatchTheLayerTitleExactly: "Jāatbilst slāņa nosaukumam tieši tā, kā tas redzams tīmekļa kartē.",
        uiCommentsTableName: "Komentāri",
        uiTokenBasedMatchUnderscoresAndSpaces: "Atbilsme uz marķiera bāzes – pasvītrojumus un atstarpes apstrādā vienādi (nejutīgs gadījums).",
        uiPhotosTableName: "Fotogrāfiju tabulas nosaukums",
        uiSurveyTableName: "Apsekojuma tabulas nosaukums",
        uiOrganizationName: "Organizācijas nosaukums",
        uiShownAsTheAuthorAndSubtitle: "Parādīts kā Excel eksporta autors un apakšvirsraksts.",
        uiHelpButtonAndGuide: "Palīdzības poga un rokasgrāmata",
        uiShowTheHelpButtonAndThe: "Rādīt palīdzības pogu un pirmās kārtas padomu",
        uiShowsAHelpButtonAtThe: "Parāda Palīdzības pogu logdaļas augšējā labajā pusē un vienreizēju padomu jauniem lietotājiem. Izslēdziet to kioskam vai iegultām vajadzībām.",
        uiRequiredWebMapSetup: "⚙️ Required Web Map Setup",
        uiTheCommentsSurveysAndPhotosTables: "Komentāriem, apsekojumiem un fotoattēliem jābūt",
        uiExplicitlyAddedToYourWebMap: "skaidri pievienots jūsu tīmekļa kartei",
        uiInPortalMapViewerPublishingThe: "portālā Map Viwer — ar FeatureServer izdošanu vien nepietiek.",
        uiOpenYourWebMapInPortal: "Atveriet savu tīmekļa karti Portālu karšu skatītājā",
        uiAddLayerBrowseTo: "Pievienot slāni → pārlūkot uz",
        uiReportaconcernManagerFeatureserver: "ZiņojumsAConcern Manager / FeatureServer",
        uiAddEachOfTheseAs: "Pievienot katru no tiem kā",
        uiTables: "Tabulas",
        uiNotLayers: "(nav slāņu):",
        uiTicketComments: "Biļetes Comments",
        uiSurveyResponses: "Apsekojuma atbildes",
        uiTicketPhotosMeta: "Biļetes Foto Meta",
        uiSaveTheWebMap: "Saglabāt tīmekļa karti",
        uiToVerify: "Lai pārbaudītu:",
        uiOpenTheBrowserConsoleAfterThe: "Atveriet pārlūka konsoli pēc logdaļu slodzes un meklējiet rindas, sākot ar",
        uiRacManager: "RKP pārvaldnieks:",
        uiNotFound: "NAV FONDS",
        uiThatTableIsMissingFromThe: ", ka tabula ir trūkst tīmekļa kartē.",
        uiAllAuthFlowsThroughThePortal: "Visa auth plūst caur Portālu sesiju — nekādas papildu žetonus nepieciešams. Lai ierobežotu piekļuvi, kopīgojiet lietotni ar Portālu grupu.",
        tickets: "Biļetes",
        eachTableShouldShowItsTitle: ". Each table should show its title — if any say"
      })
    }
  }
})
