/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        uiRacManagerSettings: "Instellingen voor RAC-beheer",
        uiMapWidget: "Mapwidget",
        uiSelectTheMapThatContainsYour: "Selecteer de kaart die uw RAC-servicelagen bevat.",
        uiTicketsLayerTitle: "Tickets Laagtitel",
        uiMustMatchTheLayerTitleExactly: "Moet exact overeenkomen met de laagtitel zoals deze in de webkaart staat.",
        uiCommentsTableName: "Opmerkingen Tabelnaam",
        uiTokenBasedMatchUnderscoresAndSpaces: "Token-gebaseerde match en spaties worden hetzelfde behandeld (case-ongevoelig).",
        uiPhotosTableName: "Foto's Tabelnaam",
        uiSurveyTableName: "Tabelnaam enquête",
        uiOrganizationName: "Naam organisatie",
        uiShownAsTheAuthorAndSubtitle: "Getoond als auteur en ondertitel van de Excel export.",
        uiHelpButtonAndGuide: "Hulpknop en gids",
        uiShowTheHelpButtonAndThe: "Toon de hulpknop en de eerste tip",
        uiShowsAHelpButtonAtThe: "Toont een Help-knop rechtsboven in het widget en een eenmalige hint voor nieuwe gebruikers. Zet het uit voor kiosk of embedded toepassingen.",
        uiRequiredWebMapSetup: "Vereiste webmap instellen",
        uiTheCommentsSurveysAndPhotosTables: "De opmerkingen, enquêtes en foto's tabellen moeten",
        uiExplicitlyAddedToYourWebMap: "expliciet toegevoegd aan uw webkaart",
        uiInPortalMapViewerPublishingThe: "in Portal Map Viewer is het publiceren van de FeatureServer alleen niet genoeg.",
        uiOpenYourWebMapInPortal: "Open uw webkaart in portaalkaartviewer",
        uiAddLayerBrowseTo: "Laag toevoegen → Bladeren naar",
        uiReportaconcernManagerFeatureserver: "ReportAConcern Manager / FeatureServer",
        uiAddEachOfTheseAs: "Voeg elk van deze als",
        uiTables: "Tabellen",
        uiNotLayers: "(geen lagen):",
        uiTicketComments: "Ticket Opmerkingen",
        uiSurveyResponses: "Onderzoek antwoorden",
        uiTicketPhotosMeta: "Ticket Foto's Meta",
        uiSaveTheWebMap: "Webkaart opslaan",
        uiToVerify: "Om te verifiëren:",
        uiOpenTheBrowserConsoleAfterThe: "Open de browserconsole na het widget laden en zoek naar regels die beginnen met",
        uiRacManager: "RAC-manager:",
        uiNotFound: "NIET GEVONDEN",
        uiThatTableIsMissingFromThe: ", die tabel ontbreekt op de webkaart.",
        uiAllAuthFlowsThroughThePortal: "Alle auth stroomt door de Portal sessie. Er zijn geen extra tokens nodig. Om de toegang te beperken, deelt u de app met een Portal-groep.",
        tickets: "Tickets",
        eachTableShouldShowItsTitle: ". Each table should show its title — if any say"
      })
    }
  }
})
