/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        uiRacManagerSettings: "RAC Manager innstillinger",
        uiMapWidget: "Kart widget",
        uiSelectTheMapThatContainsYour: "Velg kartet som inneholder dine RAC-funksjonstjenestelag.",
        uiTicketsLayerTitle: "Billetter Lagtittel",
        uiMustMatchTheLayerTitleExactly: "Må matche lagtittelen nøyaktig som den vises på webkartet.",
        uiCommentsTableName: "Kommentarer Tabellnavn",
        uiTokenBasedMatchUnderscoresAndSpaces: "Token-basert kamp - understrek og mellomrom behandles det samme (case-insensitive).",
        uiPhotosTableName: "Bilder Tabellnavn",
        uiSurveyTableName: "Undersøkelsestabellnavn",
        uiOrganizationName: "Organisasjonsnavn",
        uiShownAsTheAuthorAndSubtitle: "Vist som forfatter og undertittel til Excel-eksporten.",
        uiHelpButtonAndGuide: "Hjelp knappen og guide",
        uiShowTheHelpButtonAndThe: "Vis Hjelp-knappen og den første kjørende hinten",
        uiShowsAHelpButtonAtThe: "Viser en Hjelp-knapp øverst til høyre for widgeten og en engangs hint for nye brukere. Slå den av for kiosk eller innebygd bruk.",
        uiRequiredWebMapSetup: "⚙️ Nødvendig webkartoppsett",
        uiTheCommentsSurveysAndPhotosTables: "Kommentarer, undersøkelser og fototabeller må være",
        uiExplicitlyAddedToYourWebMap: "eksplisitt lagt til på ditt webkart",
        uiInPortalMapViewerPublishingThe: "i Portal Map Viewer - publisering av FeatureServer alene er ikke nok.",
        uiOpenYourWebMapInPortal: "Åpne webkartet i Portal Map Viewer",
        uiAddLayerBrowseTo: "Legg til lag → bla i",
        uiReportaconcernManagerFeatureserver: "ReportAConcern Manager / FeatureServer",
        uiAddEachOfTheseAs: "Legg til hver av disse som",
        uiTables: "Tabeller",
        uiNotLayers: "(ikke lag):",
        uiTicketComments: "Billett Comments",
        uiSurveyResponses: "Survey Responses",
        uiTicketPhotosMeta: "Ticket Photos Meta",
        uiSaveTheWebMap: "Lagre webkartet",
        uiToVerify: "For å bekrefte:",
        uiOpenTheBrowserConsoleAfterThe: "Åpne nettleserkonsollen etter at widgeten lastes og se etter linjer som starter med",
        uiRacManager: "RAC Manager:",
        uiNotFound: "IKKE FUND",
        uiThatTableIsMissingFromThe: "Denne tabellen mangler fra webkartet.",
        uiAllAuthFlowsThroughThePortal: "Alle aut flyter gjennom Portal-økten - ingen ekstra polletter som trengs. Hvis du vil begrense tilgangen, kan du dele appen med en portalgruppe.",
        tickets: "Billetter",
        eachTableShouldShowItsTitle: ". Each table should show its title — if any say"
      })
    }
  }
})
