/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        uiRacManagerSettings: "Ustawienia menedżera RAC",
        uiMapWidget: "Widżet mapy",
        uiSelectTheMapThatContainsYour: "Wybierz mapę zawierającą warstwy usługi RAC.",
        uiTicketsLayerTitle: "Bilety Tytuł warstwy",
        uiMustMatchTheLayerTitleExactly: "Musi pasować do tytułu warstwy dokładnie tak, jak jest na mapie.",
        uiCommentsTableName: "Uwagi Nazwa tabeli",
        uiTokenBasedMatchUnderscoresAndSpaces: "Mecz oparty na tokenach - podkreślenia i spacje są traktowane tak samo (nieczuły przypadek).",
        uiPhotosTableName: "Nazwa tabeli zdjęć",
        uiSurveyTableName: "Nazwa tabeli badania",
        uiOrganizationName: "Nazwa organizacji",
        uiShownAsTheAuthorAndSubtitle: "Pokazany jako autor i podtytuł Excel eksportu.",
        uiHelpButtonAndGuide: "Przycisk pomocy i przewodnik",
        uiShowTheHelpButtonAndThe: "Pokaż przycisk Pomoc i pierwszą podpowiedź",
        uiShowsAHelpButtonAtThe: "Pokazuje przycisk Pomoc w prawym górnym rogu widżetu i podpowiedź one- time dla nowych użytkowników. Wyłącz go dla kiosku lub wbudowanych zastosowań.",
        uiRequiredWebMapSetup: "Wymagana konfiguracja mapy internetowej",
        uiTheCommentsSurveysAndPhotosTables: "Komentarze, Badania i Zdjęcia tabele muszą być",
        uiExplicitlyAddedToYourWebMap: "wyraźnie dodane do swojej mapy",
        uiInPortalMapViewerPublishingThe: "w Portal Map Viewer - samo publikowanie FeatureServer nie wystarczy.",
        uiOpenYourWebMapInPortal: "Otwórz mapę swojej strony internetowej w Portal Mapa Viewer",
        uiAddLayerBrowseTo: "Dodaj warstwę → przeglądaj",
        uiReportaconcernManagerFeatureserver: "ReportAConcern _ Manager / FeatureServer",
        uiAddEachOfTheseAs: "Dodaj każdy z nich jako",
        uiTables: "Tabele",
        uiNotLayers: "(nie warstwy):",
        uiTicketComments: "Bilet _ Komentarze",
        uiSurveyResponses: "Badanie _ odpowiedzi",
        uiTicketPhotosMeta: "Bilet _ Zdjęcia _ Meta",
        uiSaveTheWebMap: "Zapisz mapę",
        uiToVerify: "Aby sprawdzić:",
        uiOpenTheBrowserConsoleAfterThe: "Otwórz konsolę przeglądarki po obciążeniach widget i szukaj linii zaczynających się od",
        uiRacManager: "Kierownik RAC:",
        uiNotFound: "NIE ZNALEZIONO",
        uiThatTableIsMissingFromThe: "Ten stół nie ma na mapie.",
        uiAllAuthFlowsThroughThePortal: "Cała auta przepływa przez sesję Portal - nie potrzeba dodatkowych żetonów. Aby ograniczyć dostęp, udostępniaj aplikację grupie Portal.",
        tickets: "Bilety",
        eachTableShouldShowItsTitle: ". Each table should show its title — if any say"
      })
    }
  }
})
