/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        uiRacManagerSettings: "Configurações do Gerente do RAC",
        uiMapWidget: "Widget do mapa",
        uiSelectTheMapThatContainsYour: "Selecione o mapa que contém suas camadas de serviço do RAC.",
        uiTicketsLayerTitle: "Título da Camada",
        uiMustMatchTheLayerTitleExactly: "Deve combinar com o título da camada exatamente como aparece no mapa.",
        uiCommentsTableName: "Comentários Nome da mesa",
        uiTokenBasedMatchUnderscoresAndSpaces: "Match baseado em token - sublinhados e espaços são tratados da mesma forma (caso-insensível).",
        uiPhotosTableName: "Nome da mesa de fotos",
        uiSurveyTableName: "Nome da tabela de pesquisa",
        uiOrganizationName: "Nome da organização",
        uiShownAsTheAuthorAndSubtitle: "Mostrado como autor e subtítulo da exportação do Excel.",
        uiHelpButtonAndGuide: "Botão de ajuda e guia.",
        uiShowTheHelpButtonAndThe: "Mostre o botão Ajuda e a dica de primeira execução",
        uiShowsAHelpButtonAtThe: "Mostra um botão de ajuda no canto superior direito do widget e uma dica única para novos usuários. Desligue para quiosque ou usos embutidos.",
        uiRequiredWebMapSetup: "Configuração do mapa da Web",
        uiTheCommentsSurveysAndPhotosTables: "Os comentários, pesquisas e fotos devem ser tabelas",
        uiExplicitlyAddedToYourWebMap: "explicitamente adicionado ao seu mapa web",
        uiInPortalMapViewerPublishingThe: "no Portal Map Viewer - publicar o Servidor de Recursos sozinho não é suficiente.",
        uiOpenYourWebMapInPortal: "Abra seu mapa no Visualizador de Mapas do Portal.",
        uiAddLayerBrowseTo: "Adicione camada → navegue para",
        uiReportaconcernManagerFeatureserver: "ReportAConcern Manager/FeatureServer",
        uiAddEachOfTheseAs: "Adicione cada um destes como",
        uiTables: "Tabelas",
        uiNotLayers: "(Não camadas):",
        uiTicketComments: "Comments",
        uiSurveyResponses: "\"Responsáveis\"",
        uiTicketPhotosMeta: "Ticket Photos Meta",
        uiSaveTheWebMap: "Salve o mapa da web",
        uiToVerify: "Para verificar:",
        uiOpenTheBrowserConsoleAfterThe: "Abra o console do navegador após a carga do widget e procure linhas começando com",
        uiRacManager: "Gerente da RAC:",
        uiNotFound: "NÃO ENCONTRADO",
        uiThatTableIsMissingFromThe: "Essa mesa está faltando no mapa.",
        uiAllAuthFlowsThroughThePortal: "Toda a autorização flui através da sessão do Portal - nenhum sinal extra necessário. Para restringir o acesso, compartilhe o aplicativo com um grupo do Portal.",
        tickets: "Bilhetes",
        eachTableShouldShowItsTitle: ". Each table should show its title — if any say"
      })
    }
  }
})
