/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        uiRacManagerSettings: "Configurações do Gerenciador de RAC",
        uiMapWidget: "Elemento do mapa",
        uiSelectTheMapThatContainsYour: "Selecione o mapa que contém suas camadas de serviço de recursos RAC.",
        uiTicketsLayerTitle: "Título da Camada de Bilhetes",
        uiMustMatchTheLayerTitleExactly: "Deve corresponder ao título da camada exatamente como aparece no mapa web.",
        uiCommentsTableName: "Comentários Nome da tabela",
        uiTokenBasedMatchUnderscoresAndSpaces: "Match baseado em itens — sublinhas e espaços são tratados da mesma forma (insensível ao caso).",
        uiPhotosTableName: "Nome da Tabela de Fotos",
        uiSurveyTableName: "Nome da tabela de pesquisa",
        uiOrganizationName: "Nome da organização",
        uiShownAsTheAuthorAndSubtitle: "Mostrado como o autor e subtítulo da exportação do Excel.",
        uiHelpButtonAndGuide: "Botão de ajuda e guia",
        uiShowTheHelpButtonAndThe: "Mostra o botão Ajuda e a dica de primeira execução",
        uiShowsAHelpButtonAtThe: "Mostra um botão Ajuda no canto superior direito do widget e uma dica única para novos usuários. Desligue-o para quiosque ou usos incorporados.",
        uiRequiredWebMapSetup: "Configuração do Mapa da Web Obrigatório",
        uiTheCommentsSurveysAndPhotosTables: "Os comentários, pesquisas e fotos tabelas devem ser",
        uiExplicitlyAddedToYourWebMap: "explicitamente adicionado ao seu mapa web",
        uiInPortalMapViewerPublishingThe: "no Portal Map Viewer — publicar o Servidor de Recursos sozinho não é suficiente.",
        uiOpenYourWebMapInPortal: "Abra seu mapa da web no Visualizador de Mapas do Portal",
        uiAddLayerBrowseTo: "Adicionar camada → navegar para",
        uiReportaconcernManagerFeatureserver: "ReportAConcern Manager/FeatureServer",
        uiAddEachOfTheseAs: "Adicionar cada um destes como",
        uiTables: "Tabelas",
        uiNotLayers: "(não camadas):",
        uiTicketComments: "Comentar Ticket",
        uiSurveyResponses: "Responsáveis da Pesquisa",
        uiTicketPhotosMeta: "Fotos Meta",
        uiSaveTheWebMap: "Gravar o mapa Web",
        uiToVerify: "Para verificar:",
        uiOpenTheBrowserConsoleAfterThe: "Abra o console do navegador após a carga do widget e procure por linhas começando com",
        uiRacManager: "Gestor do RAC:",
        uiNotFound: "NÃO ENCONTRADO",
        uiThatTableIsMissingFromThe: ", essa tabela está faltando no mapa web.",
        uiAllAuthFlowsThroughThePortal: "Todos os fluxos de autenticação através da sessão Portal — nenhum token extra necessário. Para restringir o acesso, compartilhe o aplicativo com um grupo do Portal.",
        tickets: "Bilhetes",
        eachTableShouldShowItsTitle: ". Each table should show its title — if any say"
      })
    }
  }
})
