/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        uiRacManagerSettings: "Configurări manager RAC",
        uiMapWidget: "Widget hartă",
        uiSelectTheMapThatContainsYour: "Selectaţi harta care conţine straturile de service RAC.",
        uiTicketsLayerTitle: "Titlu plan bilete",
        uiMustMatchTheLayerTitleExactly: "Trebuie să se potrivească cu titlul de strat exact așa cum apare în harta web.",
        uiCommentsTableName: "Comentarii Denumirea tabelului",
        uiTokenBasedMatchUnderscoresAndSpaces: "Token-based match-uri și spații sunt tratate la fel (case-insensibil).",
        uiPhotosTableName: "Numele tabelului Fotografii",
        uiSurveyTableName: "Denumirea tabelului de anchetă",
        uiOrganizationName: "Denumirea organizației",
        uiShownAsTheAuthorAndSubtitle: "Afişat ca autor şi subtitrare a exportului Excel.",
        uiHelpButtonAndGuide: "Buton de ajutor și ghid",
        uiShowTheHelpButtonAndThe: "Arată butonul Ajutor și primul indiciu",
        uiShowsAHelpButtonAtThe: "Arată un buton de ajutor la dreapta sus a widget-ului și un indiciu o singură dată pentru noi utilizatori. Opreşte-l pentru chioşc sau utilizări integrate.",
        uiRequiredWebMapSetup: "Setare hartă web necesară",
        uiTheCommentsSurveysAndPhotosTables: "Tabelele de comentarii, sondaje și fotografii trebuie să fie",
        uiExplicitlyAddedToYourWebMap: "adăugat explicit pe harta web",
        uiInPortalMapViewerPublishingThe: "în Portal Map Viewer",
        uiOpenYourWebMapInPortal: "Deschide harta web în Portal Map Viewer",
        uiAddLayerBrowseTo: "Adaugă strat → răsfoiește la",
        uiReportaconcernManagerFeatureserver: "ReportAConcern manager / FeatureServer",
        uiAddEachOfTheseAs: "Adaugă fiecare dintre acestea ca",
        uiTables: "Tabele",
        uiNotLayers: "(nu straturi):",
        uiTicketComments: "Ticket Comentarii",
        uiSurveyResponses: "Sondaj Responsiuni",
        uiTicketPhotosMeta: "Ticket Photos Meta",
        uiSaveTheWebMap: "Salvează harta web",
        uiToVerify: "Pentru a verifica:",
        uiOpenTheBrowserConsoleAfterThe: "Deschide consola browser-ului după ce widget-ul se încarcă și caută linii începând cu",
        uiRacManager: "RAC Manager:",
        uiNotFound: "NEgăsit",
        uiThatTableIsMissingFromThe: "Masa aia lipseşte din harta web.",
        uiAllAuthFlowsThroughThePortal: "Toate Auth curge prin sesiunea portalului Pentru a restrânge accesul, partajați aplicația cu un grup portal.",
        tickets: "Bilete",
        eachTableShouldShowItsTitle: ". Each table should show its title — if any say"
      })
    }
  }
})
