/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        uiRacManagerSettings: "Настройки RAC Manager",
        uiMapWidget: "Виджет карты",
        uiSelectTheMapThatContainsYour: "Выберите карту, которая содержит ваши уровни обслуживания функций RAC.",
        uiTicketsLayerTitle: "Билеты Layer Title",
        uiMustMatchTheLayerTitleExactly: "Должен соответствовать заголовку слоя точно так, как он отображается на веб-карте.",
        uiCommentsTableName: "Комментарии к названию стола",
        uiTokenBasedMatchUnderscoresAndSpaces: "Матч на основе токенов — подчеркивания и пробелы обрабатываются одинаково (случай-нечувствительный).",
        uiPhotosTableName: "Фотографии Table Name",
        uiSurveyTableName: "Обследование Table Name",
        uiOrganizationName: "Название организации",
        uiShownAsTheAuthorAndSubtitle: "Показан как автор и подзаголовок экспорта Excel.",
        uiHelpButtonAndGuide: "Кнопка помощи и руководство",
        uiShowTheHelpButtonAndThe: "Показать кнопку «Справка» и первый запуск подсказки",
        uiShowsAHelpButtonAtThe: "Показывает кнопку «Справка» в правом верхнем углу виджета и одноразовый намек для новых пользователей. Выключите его для киоска или встроенного использования.",
        uiRequiredWebMapSetup: "️ Требуется настройка веб-карты",
        uiTheCommentsSurveysAndPhotosTables: "Таблицы комментариев, обзоров и фотографий должны быть",
        uiExplicitlyAddedToYourWebMap: "явно добавлены на вашу веб-карту",
        uiInPortalMapViewerPublishingThe: "В Portal Map Viewer — публикации одного лишь FeatureServer недостаточно.",
        uiOpenYourWebMapInPortal: "Откройте свою веб-карту в Portal Map Viewer",
        uiAddLayerBrowseTo: "Добавить слой → просмотреть",
        uiReportaconcernManagerFeatureserver: "ReportAConcern Manager / FeatureServer",
        uiAddEachOfTheseAs: "Добавьте каждый из них как",
        uiTables: "Таблицы",
        uiNotLayers: "(не слоёв):",
        uiTicketComments: "Ticket Comments",
        uiSurveyResponses: "Survey Responses",
        uiTicketPhotosMeta: "Билеты Фотографии Мета",
        uiSaveTheWebMap: "Сохранить веб-карту",
        uiToVerify: "Для проверки:",
        uiOpenTheBrowserConsoleAfterThe: "Откройте консоль браузера после загрузки виджета и найдите строки, начинающиеся с",
        uiRacManager: "Менеджер RAC:",
        uiNotFound: "Не найдено",
        uiThatTableIsMissingFromThe: "Таблица отсутствует на веб-карте.",
        uiAllAuthFlowsThroughThePortal: "Весь аут проходит через сессию Портала — никаких дополнительных токенов не требуется. Чтобы ограничить доступ, поделитесь приложением с группой порталов.",
        tickets: "билеты",
        eachTableShouldShowItsTitle: ". Each table should show its title — if any say"
      })
    }
  }
})
