/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        uiRacManagerSettings: "Nastavenie správcu RAC",
        uiMapWidget: "Komponent mapy",
        uiSelectTheMapThatContainsYour: "Vyberte mapu, ktorá obsahuje vaše servisné vrstvy RAC.",
        uiTicketsLayerTitle: "Titul vrstvy vstupeniek",
        uiMustMatchTheLayerTitleExactly: "Musí zodpovedať názvu vrstvy presne tak, ako sa objaví na webovej mape.",
        uiCommentsTableName: "Poznámky Názov tabuľky",
        uiTokenBasedMatchUnderscoresAndSpaces: "Token-based match",
        uiPhotosTableName: "Meno tabuľky fotografií",
        uiSurveyTableName: "Názov tabuľky prieskumu",
        uiOrganizationName: "Názov organizácie",
        uiShownAsTheAuthorAndSubtitle: "Zobrazené ako autor a titulok exportu Excel.",
        uiHelpButtonAndGuide: "Tlačidlo pomoci a sprievodca",
        uiShowTheHelpButtonAndThe: "Zobraziť tlačidlo Pomocník a nápovedu prvého spustenia",
        uiShowsAHelpButtonAtThe: "Zobrazí tlačidlo Pomocník v pravom hornom rohu widgetu a jednorázovú radu pre nových užívateľov. Vypnite ho pre kiosk alebo vložené použitie.",
        uiRequiredWebMapSetup: "⚙️ Required Web Map Setup",
        uiTheCommentsSurveysAndPhotosTables: "Komentáre, prieskumy a tabuľky fotografií musia byť",
        uiExplicitlyAddedToYourWebMap: "explicitne pridaný do webovej mapy",
        uiInPortalMapViewerPublishingThe: "v Portal Map Viewer",
        uiOpenYourWebMapInPortal: "Otvorte svoju webovú mapu v prehliadači Portal Map",
        uiAddLayerBrowseTo: "Pridať vrstvu → prechádzať",
        uiReportaconcernManagerFeatureserver: "ReportAconcern Manager / FunkciaServer",
        uiAddEachOfTheseAs: "Pridať každý z nich ako",
        uiTables: "Tabuľky",
        uiNotLayers: "(nie vrstvy):",
        uiTicketComments: "Ticket Comment",
        uiSurveyResponses: "Prieskum Responses",
        uiTicketPhotosMeta: "Ticket Fotky Meta",
        uiSaveTheWebMap: "Uložiť webovú mapu",
        uiToVerify: "Overiť:",
        uiOpenTheBrowserConsoleAfterThe: "Otvorte konzolu prehliadača po zaťaženiach widgetu a hľadajte línie začínajúce",
        uiRacManager: "RAC manažér:",
        uiNotFound: "NEZÍSKALA",
        uiThatTableIsMissingFromThe: "Tento stôl chýba z webovej mapy.",
        uiAllAuthFlowsThroughThePortal: "Všetky auth prúdi cez Portal session Ak chcete obmedziť prístup, zdieľajte aplikáciu so skupinou portálu.",
        tickets: "Lístky",
        eachTableShouldShowItsTitle: ". Each table should show its title — if any say"
      })
    }
  }
})
