/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        uiRacManagerSettings: "Nastavitve upravitelja RAC",
        uiMapWidget: "Gradnik zemljevida",
        uiSelectTheMapThatContainsYour: "Izberite zemljevid s plastmi storitev RAC.",
        uiTicketsLayerTitle: "Vstopnice Naslov plasti",
        uiMustMatchTheLayerTitleExactly: "mora ustrezati naslovu sloja točno tako, kot se pojavi na spletnem zemljevidu.",
        uiCommentsTableName: "Opombe Ime tabele",
        uiTokenBasedMatchUnderscoresAndSpaces: "Ujemanje na podlagi simbolov – podčrtaji in prostori se obravnavajo enako (neobčutljivi).",
        uiPhotosTableName: "Ime tabele fotografij",
        uiSurveyTableName: "Ime tabele raziskave",
        uiOrganizationName: "Ime organizacije",
        uiShownAsTheAuthorAndSubtitle: "Prikazan kot avtor in podnaslov Excel izvoz.",
        uiHelpButtonAndGuide: "Gumb za pomoč in vodič",
        uiShowTheHelpButtonAndThe: "Prikaži gumb Pomoč in prvi namig",
        uiShowsAHelpButtonAtThe: "Prikaže gumb Pomoč na zgornji desni strani gradnika in enkratni namig za nove uporabnike. Ugasni ga za kiosk ali vgrajeno uporabo.",
        uiRequiredWebMapSetup: "⚙️ Required Web Map Setup",
        uiTheCommentsSurveysAndPhotosTables: "Preglednice Komentarjev, raziskav in fotografij morajo biti",
        uiExplicitlyAddedToYourWebMap: "izrecno dodan na vašo spletno karto",
        uiInPortalMapViewerPublishingThe: "v portalu Pregledovalnik zemljevidov – objava FeatureServerja sama ni dovolj.",
        uiOpenYourWebMapInPortal: "Odpri svoj spletni zemljevid v pregledovalniku zemljevidov Portala",
        uiAddLayerBrowseTo: "Dodaj plast → brskanje po",
        uiReportaconcernManagerFeatureserver: "PoročiloAconcern Manager / FeatureServer",
        uiAddEachOfTheseAs: "Dodaj vse kot",
        uiTables: "Tabele",
        uiNotLayers: "(ne plasti):",
        uiTicketComments: "Vstopnica Comment",
        uiSurveyResponses: "Reševanje odgovorov",
        uiTicketPhotosMeta: "Vstopnica Fotografije Meta",
        uiSaveTheWebMap: "Shrani spletno karto",
        uiToVerify: "Preverjanje:",
        uiOpenTheBrowserConsoleAfterThe: "Odprite konzolo brskalnika po nalaganju gradnikov in poiščite črte, ki se začnejo z",
        uiRacManager: "Upravitelj RAC:",
        uiNotFound: "NI NAŠE",
        uiThatTableIsMissingFromThe: "Ta miza manjka na spletnem zemljevidu.",
        uiAllAuthFlowsThroughThePortal: "Vsa auth teče skozi sejo Portala – brez dodatnih žetonov. Za omejitev dostopa si aplikacijo delite s skupino Portal.",
        tickets: "Vstopnice",
        eachTableShouldShowItsTitle: ". Each table should show its title — if any say"
      })
    }
  }
})
