/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        uiRacManagerSettings: "RAC Manager Inställningar",
        uiMapWidget: "Karta widget",
        uiSelectTheMapThatContainsYour: "Välj den karta som innehåller dina RAC-funktionsskikt.",
        uiTicketsLayerTitle: "Biljetter Layer Title",
        uiMustMatchTheLayerTitleExactly: "Måste matcha lager titel exakt som det visas i webbkartan.",
        uiCommentsTableName: "Kommentarer Tabellnamn",
        uiTokenBasedMatchUnderscoresAndSpaces: "Token-baserad match - understryker och utrymmen behandlas samma (fall-insensitiv).",
        uiPhotosTableName: "Bilder från Table Name",
        uiSurveyTableName: "Undersökningsbordsnamn",
        uiOrganizationName: "Organisationsnamn",
        uiShownAsTheAuthorAndSubtitle: "Visas som författare och undertext för Excel-exporten.",
        uiHelpButtonAndGuide: "Hjälp knapp och guide",
        uiShowTheHelpButtonAndThe: "Visa hjälpknappen och den första ledningen",
        uiShowsAHelpButtonAtThe: "Visar en Hjälp-knapp högst upp till höger om widgeten och en engångsint för nya användare. Stäng av det för kiosk eller inbäddade användningar.",
        uiRequiredWebMapSetup: "← Föregående Föregående inlägg: on Web Map Setup",
        uiTheCommentsSurveysAndPhotosTables: "Kommentarer, undersökningar och foton tabeller måste vara",
        uiExplicitlyAddedToYourWebMap: "uttryckligen läggs till på din webbkarta",
        uiInPortalMapViewerPublishingThe: "I Portal Map Viewer - publicering av FeatureServer ensam är inte tillräckligt.",
        uiOpenYourWebMapInPortal: "Öppna din webbkarta i Portal Map Viewer",
        uiAddLayerBrowseTo: "Lägg till lager → bläddra för att",
        uiReportaconcernManagerFeatureserver: "ReportAConcern Manager / FeatureServer",
        uiAddEachOfTheseAs: "Lägg till var och en av dessa",
        uiTables: "Tabeller",
        uiNotLayers: "(Inte lager):",
        uiTicketComments: "Ticket Comments",
        uiSurveyResponses: "Survey Responses",
        uiTicketPhotosMeta: "Ticket Photos Meta",
        uiSaveTheWebMap: "Spara webbkartan",
        uiToVerify: "För att verifiera:",
        uiOpenTheBrowserConsoleAfterThe: "Öppna webbläsarkonsolen efter widgetbelastningen och leta efter linjer som börjar med",
        uiRacManager: "RAC Manager:",
        uiNotFound: "INTE FUND",
        uiThatTableIsMissingFromThe: "Tabellen saknas från webbkartan.",
        uiAllAuthFlowsThroughThePortal: "All auth strömmar genom portalsessionen - inga extra tokens behövs. För att begränsa åtkomsten, dela appen med en portalgrupp.",
        tickets: "Biljetter",
        eachTableShouldShowItsTitle: ". Each table should show its title — if any say"
      })
    }
  }
})
