/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        uiRacManagerSettings: "ตั้งค่าโปรแกรมจัดการ RAC",
        uiMapWidget: "วิดเจ็ตของแผนที่",
        uiSelectTheMapThatContainsYour: "เลือกแผนที่ที่มีชั้นของบริการ RAC ของคุณ",
        uiTicketsLayerTitle: "เลเยอร์",
        uiMustMatchTheLayerTitleExactly: "ต้องตรงกับชื่อชั้นตามที่ปรากฏในแผนที่เว็บ",
        uiCommentsTableName: "ชื่อตารางหมายเหตุ",
        uiTokenBasedMatchUnderscoresAndSpaces: "การจับคู่แบบ Token — การเน้นเสียงและพื้นที่ ได้รับการปฏิบัติแบบเดียวกัน (ไม่ตอบสนอง)",
        uiPhotosTableName: "ชื่อตารางภาพถ่าย",
        uiSurveyTableName: "ชื่อตารางสํารวจ",
        uiOrganizationName: "ชื่อองค์กร",
        uiShownAsTheAuthorAndSubtitle: "แสดงเป็นชื่อผู้เขียนและคําบรรยายของการส่งออกเอกเซล",
        uiHelpButtonAndGuide: "ปุ่มช่วยเหลือและคําแนะนํา",
        uiShowTheHelpButtonAndThe: "แสดงปุ่มช่วยเหลือและคําใบ้การทํางานครั้งแรก",
        uiShowsAHelpButtonAtThe: "แสดงปุ่มช่วยเหลือทางด้านบนขวาของวิดเจ็ต และคําใบ้แบบหนึ่งครั้งสําหรับผู้ใช้ใหม่ ปิดการใช้กับ kiosk หรือค่าที่ฝังอยู่",
        uiRequiredWebMapSetup: "⚙️ ต้องการการตั้งค่าแผนที่เว็บ",
        uiTheCommentsSurveysAndPhotosTables: "คํา อธิบาย, การ สํารวจ, และ การ ถ่าย ภาพ ต้อง เป็น",
        uiExplicitlyAddedToYourWebMap: "เพิ่มลงในแผนที่เว็บของคุณโดยตรง",
        uiInPortalMapViewerPublishingThe: "ใน เครื่อง ดู แผนที่ พอร์ต าล — การ ตี พิมพ์ เครื่อง บิน ที่ มี คุณสมบัติ เท่า นั้น ไม่ พอ.",
        uiOpenYourWebMapInPortal: "เปิดแผนที่เว็บของคุณในเครื่องมือแสดงแผนที่ Portal",
        uiAddLayerBrowseTo: "เพิ่มเลเยอร์...",
        uiReportaconcernManagerFeatureserver: "ผู้จัดทํารายงาน",
        uiAddEachOfTheseAs: "เพิ่มแต่ละเหล่านี้เป็น",
        uiTables: "ตาราง",
        uiNotLayers: "(ไม่ใช่ชั้น):",
        uiTicketComments: "ตั๋ว",
        uiSurveyResponses: "การ สํารวจ",
        uiTicketPhotosMeta: "ตั๋ว งาน",
        uiSaveTheWebMap: "บันทึกแผนที่เว็บ",
        uiToVerify: "เพื่อตรวจสอบ:",
        uiOpenTheBrowserConsoleAfterThe: "เปิดคอนโซลของเบราว์เซอร์ หลังจากโหลดวิดเจ็ต และมองหาบรรทัดที่เริ่มด้วย",
        uiRacManager: "ตัวจัดการ RAC:",
        uiNotFound: "ไม่พบ",
        uiThatTableIsMissingFromThe: "โต๊ะนั่นหายไปจากแผนที่",
        uiAllAuthFlowsThroughThePortal: "ไม่ จําเป็น ต้อง มี เครื่องหมาย พิเศษ. เพื่อจํากัดการเข้าถึง ให้ใช้แอพร่วมกับกลุ่ม Portal",
        tickets: "ตั๋ว",
        eachTableShouldShowItsTitle: ". Each table should show its title — if any say"
      })
    }
  }
})
