/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        uiRacManagerSettings: "RAC Manager Ayarları",
        uiMapWidget: "Map widget",
        uiSelectTheMapThatContainsYour: "RAC özellik hizmet katmanlarınızı içeren haritayı seçin.",
        uiTicketsLayerTitle: "Bilet Katmanı:",
        uiMustMatchTheLayerTitleExactly: "Web haritasında göründüğü gibi katman ünvanını tam olarak eşleştirmeli.",
        uiCommentsTableName: "Yorumlar Table Name",
        uiTokenBasedMatchUnderscoresAndSpaces: "Token-based maç - alt işaretler ve alanlar aynı muamele edilir (case-in sensitive).",
        uiPhotosTableName: "Fotoğraflar Adı",
        uiSurveyTableName: "Survey Table Name",
        uiOrganizationName: "Organizasyon Adı",
        uiShownAsTheAuthorAndSubtitle: "Excel ihracatının yazarı ve alt unvanı olarak gösterin.",
        uiHelpButtonAndGuide: "Yardım düğmesine ve rehberlik",
        uiShowTheHelpButtonAndThe: "Yardım düğmesine ve ilk işletilen ipucu",
        uiShowsAHelpButtonAtThe: "Widget'nın en iyi sağında bir Yardım düğmesine ve yeni kullanıcılar için bir zaman ipucunu gösterin. Bunu kiosk veya gömülü kullanımlar için kapatın.",
        uiRequiredWebMapSetup: "Gereken Web Haritası",
        uiTheCommentsSurveysAndPhotosTables: "Yorumlar, Anketler ve Fotoğraflar masaları olmalıdır",
        uiExplicitlyAddedToYourWebMap: "Web haritanıza açıkça eklendi",
        uiInPortalMapViewerPublishingThe: "Portal Map Viewer'de - tek başına özel ilan etmek yeterli değildir.",
        uiOpenYourWebMapInPortal: "Web haritanızı Portal Map Viewer",
        uiAddLayerBrowseTo: "Add katmanı → Göze Almak",
        uiReportaconcernManagerFeatureserver: "ReportAConcern Manager / FeatureServer",
        uiAddEachOfTheseAs: "Bunların her birini ekleyin",
        uiTables: "Tablolar",
        uiNotLayers: "(Bölümler değil):",
        uiTicketComments: "Ticket Comments",
        uiSurveyResponses: "Anket Respons",
        uiTicketPhotosMeta: "Ticket Photos Meta",
        uiSaveTheWebMap: "Web haritasını kurtarın",
        uiToVerify: "Doğrulamak:",
        uiOpenTheBrowserConsoleAfterThe: "Widget yüklerinden sonra tarayıcı konsolunu açın ve hatları arayın",
        uiRacManager: "RAC Manager:",
        uiNotFound: "FOUND",
        uiThatTableIsMissingFromThe: "Ancak bu masa web haritasından eksik.",
        uiAllAuthFlowsThroughThePortal: "Portal oturumu aracılığıyla tüm auth akışlar - ekstra jetonlar gerekli değil. Erişimi kısıtlamak için, bir Portal grubu ile uygulamayı paylaşın.",
        tickets: "Bilet Bilet Biletleri Bilet",
        eachTableShouldShowItsTitle: ". Each table should show its title — if any say"
      })
    }
  }
})
