/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        uiRacManagerSettings: "Налаштування RAC Manager",
        uiMapWidget: "Карта віджет",
        uiSelectTheMapThatContainsYour: "Виберіть карту, яка містить ваші шари обслуговування RAC.",
        uiTicketsLayerTitle: "Авіаквитки Шар Назва",
        uiMustMatchTheLayerTitleExactly: "Повинна відповідати назві шарів, таким чином, як вона з'являється в веб-карті.",
        uiCommentsTableName: "Коментарі Назва таблиці",
        uiTokenBasedMatchUnderscoresAndSpaces: "Збіг на основі токенів — низи і пробіли обробляються однаковими (результатними).",
        uiPhotosTableName: "Фото Назва таблиці",
        uiSurveyTableName: "Назва таблиці",
        uiOrganizationName: "Назва організації",
        uiShownAsTheAuthorAndSubtitle: "Покажіть як автор і субтитри експорту Excel.",
        uiHelpButtonAndGuide: "Допомога кнопка і керівництво",
        uiShowTheHelpButtonAndThe: "Показати кнопку Допомога і перший підказок",
        uiShowsAHelpButtonAtThe: "Показати кнопку Допомоги у верхньому правому куті віджету та одноразовий підказок для нових користувачів. Вимкніть його для kiosk або вбудованого використання.",
        uiRequiredWebMapSetup: "浜у 涓 蹇",
        uiTheCommentsSurveysAndPhotosTables: "Коментарі, опитування та таблиці фотографій повинні бути",
        uiExplicitlyAddedToYourWebMap: "явно додано до вашої веб-карти",
        uiInPortalMapViewerPublishingThe: "в Порталі Map Viewer — видавничий редактор",
        uiOpenYourWebMapInPortal: "Відкрийте свій веб-карту на порталі Viewer",
        uiAddLayerBrowseTo: "Додати шар → переглянути",
        uiReportaconcernManagerFeatureserver: "Повідомлень про те, як ми можемо допомогти вам допомогти",
        uiAddEachOfTheseAs: "Додати кожен з них",
        uiTables: "Таблиці",
        uiNotLayers: "(не шари):",
        uiTicketComments: "Квиток",
        uiSurveyResponses: "Огляд Відповідачі",
        uiTicketPhotosMeta: "Сайт: www.svit.com",
        uiSaveTheWebMap: "Зберегти веб-карту",
        uiToVerify: "Для перевірки:",
        uiOpenTheBrowserConsoleAfterThe: "Відкрийте консоль браузера після завантаження віджету і подивіться на лінії, починаючи з",
        uiRacManager: "RAC Менеджер:",
        uiNotFound: "НЕ ЗАРАЗ",
        uiThatTableIsMissingFromThe: "Таблиця відсутній з веб-карти.",
        uiAllAuthFlowsThroughThePortal: "Всі витрати через сеанс Порталу — не потрібні додаткові токени. Щоб обмежити доступ, поділіть додаток з групою Порталу.",
        tickets: "Авіаквитки",
        eachTableShouldShowItsTitle: ". Each table should show its title — if any say"
      })
    }
  }
})
