/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        uiRacManagerSettings: "Thiết lập bộ quản lý RAC",
        uiMapWidget: "Thiết bị sơ đồ",
        uiSelectTheMapThatContainsYour: "Chọn bản đồ chứa các lớp dịch vụ đặc trưng của bạn.",
        uiTicketsLayerTitle: "Trình chọn & màu",
        uiMustMatchTheLayerTitleExactly: "Phải phù hợp với tiêu đề lớp học chính xác như nó xuất hiện trên bản đồ web.",
        uiCommentsTableName: "Bảng",
        uiTokenBasedMatchUnderscoresAndSpaces: "Phù hợp dựa trên dấu gạch chân — nhấn mạnh và dấu cách được đối xử như nhau (thường được cảm nhận).",
        uiPhotosTableName: "Bảng ảnh",
        uiSurveyTableName: "Bảng khảo sát",
        uiOrganizationName: "Tên tổ chức",
        uiShownAsTheAuthorAndSubtitle: "Hiển thị như là tác giả và phụ đề của xuất khẩu Excel.",
        uiHelpButtonAndGuide: "Nút Trợ giúp và hướng dẫn",
        uiShowTheHelpButtonAndThe: "Hiện nút Trợ giúp và gợi ý chạy đầu",
        uiShowsAHelpButtonAtThe: "Hiển thị một nút Trợ giúp ở bên phải trên cùng của ô điều khiển và gợi ý một lần cho người dùng mới. Tắt nó để dùng kiosk hay nhúng.",
        uiRequiredWebMapSetup: "Cấu hình sơ đồ trang mạng yêu cầu",
        uiTheCommentsSurveysAndPhotosTables: "Những lời bình luận, khảo sát và hình ảnh phải là",
        uiExplicitlyAddedToYourWebMap: "Rõ ràng được thêm vào bản đồ web của bạn",
        uiInPortalMapViewerPublishingThe: "trong trình xem bản đồ Portal — chỉ xuất bản cuốn Server thôi thì chưa đủ.",
        uiOpenYourWebMapInPortal: "Mở bản đồ web của bạn trong trình xem sơ đồ cổng",
        uiAddLayerBrowseTo: "Thêm lớp duyệt vào",
        uiReportaconcernManagerFeatureserver: "Báo cáo",
        uiAddEachOfTheseAs: "Thêm mỗi của những như",
        uiTables: "Bảng",
        uiNotLayers: "(không phải lớp):",
        uiTicketComments: "Vé Comment",
        uiSurveyResponses: "Khảo sát",
        uiTicketPhotosMeta: "Vé",
        uiSaveTheWebMap: "Lưu bản đồ web",
        uiToVerify: "Để xác minh:",
        uiOpenTheBrowserConsoleAfterThe: "Mở bàn điều khiển duyệt sau khi nạp ô điều khiển và tìm các dòng bắt đầu với",
        uiRacManager: "Bộ quản lý RAC:",
        uiNotFound: "Không tìm thấy",
        uiThatTableIsMissingFromThe: "Cái bàn đó bị mất trong bản đồ web.",
        uiAllAuthFlowsThroughThePortal: "Tất cả các ống dẫn đều chảy qua cổng — không cần thêm vật dụng. Để hạn chế truy cập, chia sẻ ứng dụng với một nhóm Portal.",
        tickets: "Vé",
        eachTableShouldShowItsTitle: ". Each table should show its title — if any say"
      })
    }
  }
})
