/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        uiRacManagerSettings: "RAC 管理器设置",
        uiMapWidget: "地图部件",
        uiSelectTheMapThatContainsYour: "选择包含您的 RAC 特性服务层的映射 。",
        uiTicketsLayerTitle: "门票层标题",
        uiMustMatchTheLayerTitleExactly: "必须与 Web 映射中出现的图层标题完全匹配 。",
        uiCommentsTableName: "注释表名称",
        uiTokenBasedMatchUnderscoresAndSpaces: "基于托肯的匹配——强调和空格处理相同(对大小写不敏感).",
        uiPhotosTableName: "相片表名称",
        uiSurveyTableName: "调查表名称",
        uiOrganizationName: "组织名称",
        uiShownAsTheAuthorAndSubtitle: "显示为 Excel 导出 的作者和字幕 。",
        uiHelpButtonAndGuide: "帮助按钮和引导",
        uiShowTheHelpButtonAndThe: "显示帮助按钮和首发提示",
        uiShowsAHelpButtonAtThe: "在部件右上方显示一个帮助按钮,并为新用户显示一次性提示。 关闭它用于亭或嵌入式用途.",
        uiRequiredWebMapSetup: "需要的网页映射设置",
        uiTheCommentsSurveysAndPhotosTables: "评论、调查和照片表必须是:",
        uiExplicitlyAddedToYourWebMap: "明确添加到您的网络地图中",
        uiInPortalMapViewerPublishingThe: "在\"Portal Map Viewer\"中——仅出版\"FeatureServer\"是不够的.",
        uiOpenYourWebMapInPortal: "在 Portal 地图查看器中打开您的网络地图",
        uiAddLayerBrowseTo: "添加层 ~ 浏览到",
        uiReportaconcernManagerFeatureserver: "报告AConcern 管理器/功能服务器",
        uiAddEachOfTheseAs: "添加每个",
        uiTables: "表",
        uiNotLayers: "(不是分层):",
        uiTicketComments: "车票( Comments)",
        uiSurveyResponses: "调查 答复",
        uiTicketPhotosMeta: "车票( P)",
        uiSaveTheWebMap: "保存网络映射",
        uiToVerify: "核实:",
        uiOpenTheBrowserConsoleAfterThe: "在部件加载后打开浏览器控制台, 并查找起始线",
        uiRacManager: "RAC 管理器 :",
        uiNotFound: "没有找到",
        uiThatTableIsMissingFromThe: ",该表在网络地图上缺失。",
        uiAllAuthFlowsThroughThePortal: "所有认证都流经了门户会话——不需要额外的符号. 为了限制访问,与一个门户网站组共享该应用程序.",
        tickets: "车票",
        eachTableShouldShowItsTitle: ". Each table should show its title — if any say"
      })
    }
  }
})
