/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        uiRacManagerSettings: "RAC 管理器設定",
        uiMapWidget: "地圖元件",
        uiSelectTheMapThatContainsYour: "選擇包含您 RAC 特性服務層的地圖 。",
        uiTicketsLayerTitle: "出票層標題",
        uiMustMatchTheLayerTitleExactly: "必須和網頁地圖上所顯示的地層標題相匹配 。",
        uiCommentsTableName: "註解表名稱",
        uiTokenBasedMatchUnderscoresAndSpaces: "有相通相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相接相相相接相接相相接相相接相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相相",
        uiPhotosTableName: "相片表格名稱",
        uiSurveyTableName: "調查表名稱",
        uiOrganizationName: "組織名稱",
        uiShownAsTheAuthorAndSubtitle: "在 Excel 匯出中以作者和字幕顯示 。",
        uiHelpButtonAndGuide: "說明按鍵和指導",
        uiShowTheHelpButtonAndThe: "顯示說明按鍵和 第一個執行的提示",
        uiShowsAHelpButtonAtThe: "在元件最右上方顯示說明按鍵并一次性提示新用戶 。 關掉取出站或嵌入式用具",
        uiRequiredWebMapSetup: "需要的網頁地圖設定",
        uiTheCommentsSurveysAndPhotosTables: "第 二 章",
        uiExplicitlyAddedToYourWebMap: "在您的網頁地圖中已明确添加",
        uiInPortalMapViewerPublishingThe: "在 Portal 地圖檢視器中 -- -- 單獨出自地物伺服器是不够的。",
        uiOpenYourWebMapInPortal: "在 Portal 地圖檢視器中開啟您的網頁地圖",
        uiAddLayerBrowseTo: "新增地層 ~ 瀏覽到",
        uiReportaconcernManagerFeatureserver: "報告( A)",
        uiAddEachOfTheseAs: "相加相加",
        uiTables: "表格",
        uiNotLayers: "(不是分層):",
        uiTicketComments: "二. 出票( P)",
        uiSurveyResponses: "調查( R)",
        uiTicketPhotosMeta: "出票( P)",
        uiSaveTheWebMap: "儲存網頁地圖",
        uiToVerify: "以核实:",
        uiOpenTheBrowserConsoleAfterThe: "在元件載入后開啟瀏覽器控制台并從頭尋找行",
        uiRacManager: "RAC 管理員 :",
        uiNotFound: "找不到",
        uiThatTableIsMissingFromThe: "在網頁地圖上找不到這個表格 。",
        uiAllAuthFlowsThroughThePortal: "所有憑證都通通了通訊口通訊口- 不需要額外的代碼 。 为限制取用, 請與 Portal 群組相通 。",
        tickets: "票",
        eachTableShouldShowItsTitle: ". Each table should show its title — if any say"
      })
    }
  }
})
